[package]
name = "openzt"
version = "0.1.0-alpha"
edition = "2021" # Test on the latest edition, will need to wrap all Repr(c) with unsafe and likely other changes
# default-target = "i686-pc-windows-msvc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[dependencies]
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
retour = {version = "0.3.1", features = ["thiscall-abi"]} # Test with v0.4.0-alpha.3 can we do without nightly now?
retour-utils = "0.2.1"
once_cell = "1.21.3"
num_enum = "0.7.3"
walkdir = "2.5.0"
zip = "=2.3.0" # TODO: Update to latest
bf_configparser = { git = "https://github.com/openztcc/bf-configparser", version = "1.1.1", features = ["indexmap"]}
anyhow = "1.0.98"
getset = "0.1.5"
maplit = "1.0.2"
field_accessor_as_string = { path = "libs/field_accessor_as_string" }
field_accessor_as_string_trait = { path = "libs/field_accessor_as_string_trait" }
serde = {version = "1.0.219", features = ["derive"]}
toml = "0.8.22"
regex = "1.11.1"
public = "0.2.2"
windows = { version = "0.61.1", features = ["Win32", "Win32_System_Console", "Win32_System_SystemServices", "Win32_System_Memory", ] }
enable-ansi-support = "0.2.1"
nt-time = "=0.10.6"
log = "0.4.27"

[lib]
name = "openzt"
crate-type = ["cdylib"]

[[bin]]
name = "test"
path = "src/debug_dll.rs"

[features]
default = ["experimental", "ini"]
release = []
ini = []
capture_ztlog = []
experimental = []

[workspace.metadata.cross.target.i686-pc-windows-msvc]
image = "ghcr.io/cross-rs/i686-pc-windows-msvc-cross:local"
#[workspace.metadata.cross.build]
#pre-build = ["ls"]