// Auto-generated by rust_struct_exporter.py
// Do not edit manually
use std::ffi::c_void;

// Size: 0x1e (30 bytes)
#[repr(C)]
pub struct AISettings {
    pub map_size: i32,  // offset: 0x0000
    pub min_cost: i32,  // offset: 0x0004
    pub node_max: i32,  // offset: 0x0008
    pub cost_max: i32,  // offset: 0x000c
    pub vector_increment: i32,  // offset: 0x0010
    pub heuristic: f32,  // offset: 0x0014
    pub estimate_func: i32,  // offset: 0x0018
    pub allow_diagonal_moves: bool,  // offset: 0x001c
    pub mbr_0x1d: u8,  // offset: 0x001d
}

// Size: 0x8c (140 bytes)
#[repr(C)]
pub struct AI_cls_0x404fd6 {
    pub cls_0x40143b: BFTile,  // offset: 0x0000
}

// Size: 0x18 (24 bytes)
#[repr(C)]
pub struct Ambients {
    pub mbr_0x0: u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
}

// Size: 0x150 (336 bytes)
#[repr(C)]
pub struct BFAIMgr {
    _pad_0x0000: [u8; 4],
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0005: [u8; 3],
    pub mbr_0x8: u8,  // offset: 0x0008
    _pad_0x000c: [u8; 268],
    pub mbr_0x118: u8,  // offset: 0x0118
    pub mbr_0x11c: u8,  // offset: 0x011c
    pub mbr_0x120: u8,  // offset: 0x0120
    _pad_0x0121: [u8; 3],
    pub mbr_0x124: u8,  // offset: 0x0124
    pub mbr_0x128: u8,  // offset: 0x0128
    pub mbr_0x12c: u8,  // offset: 0x012c
    pub mbr_0x130: u8,  // offset: 0x0130
    pub mbr_0x134: u8,  // offset: 0x0134
    _pad_0x0135: [u8; 27],
}

// Size: 0x514 (1300 bytes)
#[repr(C)]
pub struct BFApp {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x6: u8,  // offset: 0x0006
    pub mbr_0x8: u8,  // offset: 0x0008
    _pad_0x000c: [u8; 4],
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x29: u8,  // offset: 0x0029
    _pad_0x002d: [u8; 508],
    pub mbr_0x229: u8,  // offset: 0x0229
    _pad_0x022d: [u8; 511],
    pub mbr_0x42c: u8,  // offset: 0x042c
    pub mbr_0x430: u8,  // offset: 0x0430
    pub mbr_0x434: u8,  // offset: 0x0434
    pub mbr_0x438: u8,  // offset: 0x0438
    pub mbr_0x43c: u8,  // offset: 0x043c
    pub mbr_0x440: u8,  // offset: 0x0440
    pub mbr_0x441: u8,  // offset: 0x0441
    pub mbr_0x442: u8,  // offset: 0x0442
    _pad_0x0443: [u8; 1],
    pub mbr_0x444: u8,  // offset: 0x0444
    pub mbr_0x446: u8,  // offset: 0x0446
    _pad_0x0447: [u8; 1],
    pub mbr_0x448: u8,  // offset: 0x0448
    pub mbr_0x44c: u8,  // offset: 0x044c
    pub mbr_0x450: u8,  // offset: 0x0450
    pub mbr_0x454: u8,  // offset: 0x0454
    pub mbr_0x458: u8,  // offset: 0x0458
    pub mbr_0x45c: u8,  // offset: 0x045c
    pub mbr_0x460: u8,  // offset: 0x0460
    _pad_0x0464: [u8; 64],
    pub mbr_0x4a4: u8,  // offset: 0x04a4
    pub mbr_0x4a5: u8,  // offset: 0x04a5
    _pad_0x04a6: [u8; 2],
    pub mbr_0x4a8: u8,  // offset: 0x04a8
    pub mbr_0x4ac: u8,  // offset: 0x04ac
    pub mbr_0x4b0: u8,  // offset: 0x04b0
    pub mbr_0x4b4: u8,  // offset: 0x04b4
    pub mbr_0x4b8: u8,  // offset: 0x04b8
    pub mbr_0x4bc: u8,  // offset: 0x04bc
    pub mbr_0x4c0: u8,  // offset: 0x04c0
    pub mbr_0x4c4: u8,  // offset: 0x04c4
    pub mbr_0x4c8: u8,  // offset: 0x04c8
    pub mbr_0x4cc: u8,  // offset: 0x04cc
    pub mbr_0x4d0: u8,  // offset: 0x04d0
    _pad_0x04d1: [u8; 3],
    pub mbr_0x4d4: u8,  // offset: 0x04d4
    pub mbr_0x4d8: u8,  // offset: 0x04d8
    pub mbr_0x4dc: u8,  // offset: 0x04dc
    _pad_0x04e0: [u8; 12],
    pub mbr_0x4ec: u8,  // offset: 0x04ec
    pub mbr_0x4f0: u8,  // offset: 0x04f0
    pub mbr_0x4f4: u8,  // offset: 0x04f4
    pub mbr_0x4f8: u8,  // offset: 0x04f8
    pub mbr_0x4fc: u8,  // offset: 0x04fc
    pub mbr_0x500: u8,  // offset: 0x0500
    pub mbr_0x504: u8,  // offset: 0x0504
    pub mbr_0x508: u8,  // offset: 0x0508
    pub mbr_0x509: u8,  // offset: 0x0509
    _pad_0x050a: [u8; 2],
    pub mbr_0x50c: u8,  // offset: 0x050c
    pub mbr_0x510: u8,  // offset: 0x0510
}

// Size: 0x1 (1 bytes)
#[repr(C)]
pub struct BFBSCall {
    _pad_0x0000: [u8; 1],
}

// Size: 0x60 (96 bytes)
#[repr(C)]
pub struct BFCogGoal {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x2c: u8,  // offset: 0x002c
    pub mbr_0x30: u8,  // offset: 0x0030
    pub mbr_0x34: u8,  // offset: 0x0034
    pub mbr_0x38: u8,  // offset: 0x0038
    pub mbr_0x3c: u8,  // offset: 0x003c
    pub mbr_0x40: u8,  // offset: 0x0040
    pub mbr_0x44: u8,  // offset: 0x0044
    pub mbr_0x48: u8,  // offset: 0x0048
    pub mbr_0x4c: u8,  // offset: 0x004c
    pub mbr_0x50: u8,  // offset: 0x0050
    pub mbr_0x54: u8,  // offset: 0x0054
    pub mbr_0x58: u8,  // offset: 0x0058
    pub mbr_0x5c: u8,  // offset: 0x005c
}

// Size: 0x5c (92 bytes)
#[repr(C)]
pub struct BFConfigFile {
    pub cls_0x4012a6: std_tree,  // offset: 0x0000
}

// Size: 0x154 (340 bytes)
#[repr(C)]
pub struct BFEntity {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x11: u8,  // offset: 0x0011
    _pad_0x0012: [u8; 2],
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    _pad_0x0020: [u8; 188],
    pub mbr_0xdc: u8,  // offset: 0x00dc
    pub mbr_0xe0: u8,  // offset: 0x00e0
    pub mbr_0xe4: u8,  // offset: 0x00e4
    pub mbr_0xe8: u8,  // offset: 0x00e8
    _pad_0x00e9: [u8; 3],
    pub mbr_0xec: u8,  // offset: 0x00ec
    _pad_0x00f0: [u8; 4],
    pub mbr_0xf4: u8,  // offset: 0x00f4
    pub mbr_0xf8: u8,  // offset: 0x00f8
    pub mbr_0xf9: u8,  // offset: 0x00f9
    _pad_0x00fa: [u8; 2],
    pub mbr_0xfc: u8,  // offset: 0x00fc
    pub mbr_0x100: u8,  // offset: 0x0100
    pub mbr_0x104: u8,  // offset: 0x0104
    pub mbr_0x108: u8,  // offset: 0x0108
    pub mbr_0x10c: u8,  // offset: 0x010c
    pub mbr_0x110: u8,  // offset: 0x0110
    pub x_coord: u8,  // offset: 0x0114
    pub y_coord: u8,  // offset: 0x0118
    pub z_coord: u8,  // offset: 0x011c
    pub height_above_terrain: u8,  // offset: 0x0120
    pub mbr_0x124: u8,  // offset: 0x0124
    pub entity_type: *const *const u8,  // offset: 0x0128
    pub rotation: u8,  // offset: 0x012c
    pub mbr_0x130: u8,  // offset: 0x0130
    pub mbr_0x134: u8,  // offset: 0x0134
    pub mbr_0x138: u8,  // offset: 0x0138
    pub mbr_0x13c: u8,  // offset: 0x013c
    pub mbr_0x13d: u8,  // offset: 0x013d
    pub mbr_0x13e: u8,  // offset: 0x013e
    pub visible: u8,  // offset: 0x013f
    pub snap_to_ground: u8,  // offset: 0x0140
    pub selected: u8,  // offset: 0x0141
    pub mbr_0x142: u8,  // offset: 0x0142
    pub mbr_0x143: u8,  // offset: 0x0143
    pub draw_dithered: u8,  // offset: 0x0144
    pub mbr_0x145: u8,  // offset: 0x0145
    pub stop_at_end: u8,  // offset: 0x0146
    _pad_0x0147: [u8; 1],
    pub mbr_0x148: u8,  // offset: 0x0148
    pub mbr_0x14c: u8,  // offset: 0x014c
    pub mbr_0x150: u8,  // offset: 0x0150
}

// Size: 0x100 (256 bytes)
#[repr(C)]
pub struct BFEntityType {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x2c: u8,  // offset: 0x002c
    pub mbr_0x30: u8,  // offset: 0x0030
    _pad_0x0034: [u8; 4],
    pub mbr_0x38: u8,  // offset: 0x0038
    pub mbr_0x3c: u8,  // offset: 0x003c
    pub mbr_0x40: u8,  // offset: 0x0040
    pub mbr_0x44: u8,  // offset: 0x0044
    pub mbr_0x48: u8,  // offset: 0x0048
    pub mbr_0x4c: u8,  // offset: 0x004c
    pub mbr_0x50: u8,  // offset: 0x0050
    pub mbr_0x54: u8,  // offset: 0x0054
    pub mbr_0x55: u8,  // offset: 0x0055
    pub mbr_0x56: u8,  // offset: 0x0056
    pub mbr_0x57: u8,  // offset: 0x0057
    pub mbr_0x58: u8,  // offset: 0x0058
    pub mbr_0x59: u8,  // offset: 0x0059
    pub mbr_0x5a: u8,  // offset: 0x005a
    pub mbr_0x5b: u8,  // offset: 0x005b
    pub mbr_0x5c: u8,  // offset: 0x005c
    pub mbr_0x5d: u8,  // offset: 0x005d
    pub mbr_0x5e: u8,  // offset: 0x005e
    _pad_0x005f: [u8; 1],
    pub mbr_0x60: u8,  // offset: 0x0060
    _pad_0x0061: [u8; 3],
    pub mbr_0x64: u8,  // offset: 0x0064
    pub mbr_0x68: u8,  // offset: 0x0068
    pub mbr_0x6c: u8,  // offset: 0x006c
    pub mbr_0x6d: u8,  // offset: 0x006d
    pub mbr_0x6e: u8,  // offset: 0x006e
    pub mbr_0x6f: u8,  // offset: 0x006f
    pub mbr_0x70: u8,  // offset: 0x0070
    pub mbr_0x74: u8,  // offset: 0x0074
    pub mbr_0x78: u8,  // offset: 0x0078
    pub mbr_0x7c: u8,  // offset: 0x007c
    _pad_0x0080: [u8; 52],
    pub footprint_x: u32,  // offset: 0x00b4
    pub footprint_y: u32,  // offset: 0x00b8
    pub footprint_z: u32,  // offset: 0x00bc
    pub placement_footprint_x: u32,  // offset: 0x00c0
    pub placement_footprint_y: u32,  // offset: 0x00c4
    pub placement_footprint_z: u32,  // offset: 0x00c8
    pub available: i8,  // offset: 0x00cc
    _pad_0x00cd: [u8; 51],
}

// Size: 0x1c (28 bytes)
#[repr(C)]
pub struct BFEvent {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x16: u8,  // offset: 0x0016
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1a: u8,  // offset: 0x001a
    pub mbr_0x1b: u8,  // offset: 0x001b
}

// Size: 0x1 (1 bytes)
#[repr(C)]
pub struct BFEventInfo {
    _pad_0x0000: [u8; 1],
}

// Size: 0x20 (32 bytes)
#[repr(C)]
pub struct BFFontDescription {
    _pad_0x0000: [u8; 20],
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
}

// Size: 0x514 (1300 bytes)
#[repr(C)]
pub struct BFGameApp {
    pub cls_0x630908: *const u8,  // offset: 0x0000
}

// Size: 0x4 (4 bytes)
#[repr(C)]
pub struct BFGoalFactory {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
}

// Size: 0xf0 (240 bytes)
#[repr(C)]
pub struct BFMap {
    pub mbr_0x0: u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x2c: u8,  // offset: 0x002c
    pub mbr_0x30: u8,  // offset: 0x0030
    pub mbr_0x34: u8,  // offset: 0x0034
    _pad_0x0035: [u8; 1],
    pub mbr_0x36: u8,  // offset: 0x0036
    pub mbr_0x38: u8,  // offset: 0x0038
    _pad_0x003c: [u8; 180],
}

// Size: 0xc (12 bytes)
#[repr(C)]
pub struct BFMoveMod {
    _pad_0x0000: [u8; 8],
    pub mbr_0x8: u8,  // offset: 0x0008
}

// Size: 0x1 (1 bytes)
#[repr(C)]
pub struct BFObject {
    _pad_0x0000: [u8; 1],
}

// Size: 0x154 (340 bytes)
#[repr(C)]
pub struct BFOverlay {
    pub cls_0x62d4b4: *const u8,  // offset: 0x0000
}

// Size: 0x144 (324 bytes)
#[repr(C)]
pub struct BFOverlayType {
    pub cls_0x62e28c: *const u8,  // offset: 0x0000
    _pad_0x0100: [u8; 68],
}

// Size: 0xc (12 bytes)
#[repr(C)]
pub struct BFPos {
    pub x: u32,  // offset: 0x0000
    pub y: u32,  // offset: 0x0004
    pub z: u32,  // offset: 0x0008
}

// Size: 0x8 (8 bytes)
#[repr(C)]
pub struct BFRegistry {
    pub mbr_0x0: u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
}

// Size: 0x1c (28 bytes)
#[repr(C)]
pub struct BFResourceDir {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub num_resources: u32,  // offset: 0x0010
    _pad_0x0014: [u8; 8],
}

// Size: 0x15 (21 bytes)
#[repr(C)]
pub struct BFResourceMgr {
    pub mbr_0x0: u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    _pad_0x0014: [u8; 1],
}

// Size: 0x14 (20 bytes)
#[repr(C)]
pub struct BFResourcePtr {
    _pad_0x0000: [u8; 12],
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
}

// Size: 0x18 (24 bytes)
#[repr(C)]
pub struct BFResourceZip {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    _pad_0x000d: [u8; 3],
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
}

// Size: 0x94 (148 bytes)
#[repr(C)]
pub struct BFScenarioMgr {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0005: [u8; 143],
}

// Size: 0x8c (140 bytes)
#[repr(C)]
pub struct BFTile {
    _pad_0x0000: [u8; 52],
    pub x_pos: i32,  // offset: 0x0034
    pub y_pos: i32,  // offset: 0x0038
    _pad_0x003c: [u8; 64],
    pub mbr_0x7c: u8,  // offset: 0x007c
    pub mbr_0x7d: u8,  // offset: 0x007d
    _pad_0x007e: [u8; 2],
    pub mbr_0x80: u8,  // offset: 0x0080
    pub mbr_0x84: u8,  // offset: 0x0084
    pub mbr_0x85: u8,  // offset: 0x0085
    pub mbr_0x86: u8,  // offset: 0x0086
    pub mbr_0x87: u8,  // offset: 0x0087
    pub mbr_0x88: u8,  // offset: 0x0088
}

// Size: 0x170 (368 bytes)
#[repr(C)]
pub struct BFUIMgr {
    pub mbr_0x0: u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0005: [u8; 3],
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x2c: u8,  // offset: 0x002c
    pub mbr_0x30: u8,  // offset: 0x0030
    pub mbr_0x34: u8,  // offset: 0x0034
    pub mbr_0x38: u8,  // offset: 0x0038
    pub mbr_0x3c: u8,  // offset: 0x003c
    _pad_0x0040: [u8; 4],
    pub mbr_0x44: u8,  // offset: 0x0044
    _pad_0x0048: [u8; 8],
    pub mbr_0x50: u8,  // offset: 0x0050
    pub mbr_0x54: u8,  // offset: 0x0054
    pub mbr_0x58: u8,  // offset: 0x0058
    pub mbr_0x5c: u8,  // offset: 0x005c
    _pad_0x005d: [u8; 3],
    pub mbr_0x60: u8,  // offset: 0x0060
    _pad_0x0064: [u8; 12],
    pub mbr_0x70: u8,  // offset: 0x0070
    pub mbr_0x74: u8,  // offset: 0x0074
    pub mbr_0x78: u8,  // offset: 0x0078
    pub mbr_0x7c: u8,  // offset: 0x007c
    _pad_0x0080: [u8; 8],
    pub mbr_0x88: u8,  // offset: 0x0088
    _pad_0x008c: [u8; 4],
    pub mbr_0x90: u8,  // offset: 0x0090
    pub mbr_0x94: u8,  // offset: 0x0094
    pub mbr_0x98: u8,  // offset: 0x0098
    _pad_0x009c: [u8; 108],
    pub mbr_0x108: u8,  // offset: 0x0108
    _pad_0x010c: [u8; 28],
    pub mbr_0x128: u8,  // offset: 0x0128
    pub mbr_0x129: u8,  // offset: 0x0129
    pub mbr_0x12a: u8,  // offset: 0x012a
    pub mbr_0x12b: u8,  // offset: 0x012b
    pub mbr_0x12c: u8,  // offset: 0x012c
    _pad_0x012d: [u8; 3],
    pub mbr_0x130: u8,  // offset: 0x0130
    _pad_0x0134: [u8; 4],
    pub mbr_0x138: u8,  // offset: 0x0138
    pub mbr_0x13c: u8,  // offset: 0x013c
    pub mbr_0x140: u8,  // offset: 0x0140
    _pad_0x0144: [u8; 4],
    pub mbr_0x148: u8,  // offset: 0x0148
    pub mbr_0x14c: u8,  // offset: 0x014c
    pub mbr_0x150: u8,  // offset: 0x0150
    _pad_0x0154: [u8; 4],
    pub mbr_0x158: u8,  // offset: 0x0158
    _pad_0x015c: [u8; 8],
    pub mbr_0x164: u8,  // offset: 0x0164
    pub mbr_0x168: u8,  // offset: 0x0168
    pub mbr_0x16c: u8,  // offset: 0x016c
}

// Size: 0x214 (532 bytes)
#[repr(C)]
pub struct BFUnit {
    pub cls_0x62d4b4: *const u8,  // offset: 0x0000
    pub mbr_0x154: u8,  // offset: 0x0154
    pub mbr_0x158: u8,  // offset: 0x0158
    pub cls_0x635430: *const u8,  // offset: 0x015c
    pub mbr_0x1bc: u8,  // offset: 0x01bc
    pub mbr_0x1c0: u8,  // offset: 0x01c0
    pub mbr_0x1c4: u8,  // offset: 0x01c4
    pub mbr_0x1c8: u8,  // offset: 0x01c8
    _pad_0x01cc: [u8; 4],
    pub mbr_0x1d0: u8,  // offset: 0x01d0
    _pad_0x01d4: [u8; 4],
    pub mbr_0x1d8: u8,  // offset: 0x01d8
    pub mbr_0x1dc: u8,  // offset: 0x01dc
    pub mbr_0x1e0: u8,  // offset: 0x01e0
    pub mbr_0x1e4: u8,  // offset: 0x01e4
    pub mbr_0x1e8: u8,  // offset: 0x01e8
    pub mbr_0x1ec: u8,  // offset: 0x01ec
    pub mbr_0x1f0: u8,  // offset: 0x01f0
    pub mbr_0x1f4: u8,  // offset: 0x01f4
    pub mbr_0x1f8: u8,  // offset: 0x01f8
    pub mbr_0x1fc: u8,  // offset: 0x01fc
    pub mbr_0x200: u8,  // offset: 0x0200
    pub mbr_0x204: u8,  // offset: 0x0204
    pub mbr_0x208: u8,  // offset: 0x0208
    pub mbr_0x20c: u8,  // offset: 0x020c
    pub mbr_0x210: u8,  // offset: 0x0210
    _pad_0x0211: [u8; 3],
}

// Size: 0x144 (324 bytes)
#[repr(C)]
pub struct BFUnitType {
    pub cls_0x62e28c: *const u8,  // offset: 0x0000
    _pad_0x0100: [u8; 68],
}

// Size: 0x118 (280 bytes)
#[repr(C)]
pub struct BFWorldMgr {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0005: [u8; 47],
    pub map_x_size: i32,  // offset: 0x0034
    pub map_y_size: i32,  // offset: 0x0038
    _pad_0x003c: [u8; 4],
    pub tile_array: i32,  // offset: 0x0040
    _pad_0x0044: [u8; 212],
}

// Size: 0x94 (148 bytes)
#[repr(C)]
pub struct DX8SndMgr {
    _pad_0x0000: [u8; 4],
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0005: [u8; 143],
}

// Size: 0x24 (36 bytes)
#[repr(C)]
pub struct DX8Sound {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    _pad_0x001d: [u8; 3],
    pub mbr_0x20: u8,  // offset: 0x0020
}

// Size: 0x98 (152 bytes)
#[repr(C)]
pub struct GXCanvas {
    pub mbr_0x0: u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0008: [u8; 4],
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    _pad_0x0018: [u8; 16],
    pub mbr_0x28: u8,  // offset: 0x0028
    _pad_0x002c: [u8; 24],
    pub mbr_0x44: u8,  // offset: 0x0044
    pub mbr_0x48: u8,  // offset: 0x0048
    _pad_0x004c: [u8; 12],
    pub mbr_0x58: u8,  // offset: 0x0058
    pub mbr_0x5c: u8,  // offset: 0x005c
    pub mbr_0x60: u8,  // offset: 0x0060
    pub mbr_0x64: u8,  // offset: 0x0064
    pub mbr_0x68: u8,  // offset: 0x0068
    _pad_0x006c: [u8; 20],
    pub mbr_0x80: u8,  // offset: 0x0080
    pub mbr_0x84: u8,  // offset: 0x0084
    pub mbr_0x88: u8,  // offset: 0x0088
    pub mbr_0x8c: u8,  // offset: 0x008c
    pub mbr_0x90: u8,  // offset: 0x0090
    pub mbr_0x94: u8,  // offset: 0x0094
}

// Size: 0x19 (25 bytes)
#[repr(C)]
pub struct GXLLEAnim {
    pub mbr_0x0: u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
}

// Size: 0x65 (101 bytes)
#[repr(C)]
pub struct GXMixer {
    pub mbr_0x0: u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x2c: u8,  // offset: 0x002c
    pub mbr_0x30: u8,  // offset: 0x0030
    pub mbr_0x34: u8,  // offset: 0x0034
    pub mbr_0x38: u8,  // offset: 0x0038
    pub mbr_0x3c: u8,  // offset: 0x003c
    pub mbr_0x40: u8,  // offset: 0x0040
    pub mbr_0x44: u8,  // offset: 0x0044
    pub mbr_0x48: u8,  // offset: 0x0048
    pub mbr_0x4c: u8,  // offset: 0x004c
    pub mbr_0x50: u8,  // offset: 0x0050
    pub mbr_0x54: u8,  // offset: 0x0054
    pub mbr_0x58: u8,  // offset: 0x0058
    pub mbr_0x5c: u8,  // offset: 0x005c
    pub mbr_0x60: u8,  // offset: 0x0060
    pub mbr_0x61: u8,  // offset: 0x0061
    pub mbr_0x62: u8,  // offset: 0x0062
    pub mbr_0x63: u8,  // offset: 0x0063
    pub mbr_0x64: u8,  // offset: 0x0064
}

// Size: 0x8 (8 bytes)
#[repr(C)]
pub struct SNDSound {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
}

// Size: 0x8 (8 bytes)
#[repr(C)]
pub struct SNDSoundResource {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
}

// Size: 0x10 (16 bytes)
#[repr(C)]
pub struct SNDSoundResourceWAV {
    pub cls_0x635218: *const u8,  // offset: 0x0000
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
}

// Size: 0x180d (6157 bytes)
#[repr(C)]
pub struct Sorter {
    pub mbr_0x0: u8,  // offset: 0x0000
    _pad_0x0004: [u8; 304],
    pub mbr_0x134: u8,  // offset: 0x0134
    _pad_0x0138: [u8; 12],
    pub mbr_0x144: u8,  // offset: 0x0144
    _pad_0x0145: [u8; 5435],
    pub mbr_0x1680: u8,  // offset: 0x1680
    pub mbr_0x1684: u8,  // offset: 0x1684
    pub mbr_0x1688: u8,  // offset: 0x1688
    pub mbr_0x168c: u8,  // offset: 0x168c
    pub mbr_0x1690: u8,  // offset: 0x1690
    pub mbr_0x1694: u8,  // offset: 0x1694
    pub mbr_0x1698: u8,  // offset: 0x1698
    _pad_0x169c: [u8; 12],
    pub mbr_0x16a8: u8,  // offset: 0x16a8
    pub mbr_0x16ac: u8,  // offset: 0x16ac
    pub mbr_0x16b0: u8,  // offset: 0x16b0
    pub mbr_0x16b4: u8,  // offset: 0x16b4
    pub mbr_0x16b8: u8,  // offset: 0x16b8
    pub mbr_0x16bc: u8,  // offset: 0x16bc
    pub mbr_0x16c0: u8,  // offset: 0x16c0
    pub mbr_0x16c4: u8,  // offset: 0x16c4
    pub mbr_0x16c8: u8,  // offset: 0x16c8
    pub mbr_0x16cc: u8,  // offset: 0x16cc
    pub mbr_0x16d0: u8,  // offset: 0x16d0
    pub mbr_0x16d4: u8,  // offset: 0x16d4
    pub mbr_0x16d8: u8,  // offset: 0x16d8
    pub mbr_0x16dc: u8,  // offset: 0x16dc
    pub mbr_0x16e0: u8,  // offset: 0x16e0
    pub mbr_0x16e4: u8,  // offset: 0x16e4
    pub mbr_0x16e8: u8,  // offset: 0x16e8
    pub mbr_0x16ec: u8,  // offset: 0x16ec
    pub mbr_0x16f0: u8,  // offset: 0x16f0
    _pad_0x16f4: [u8; 4],
    pub mbr_0x16f8: u8,  // offset: 0x16f8
    _pad_0x16fc: [u8; 260],
    pub mbr_0x1800: u8,  // offset: 0x1800
    pub mbr_0x1804: u8,  // offset: 0x1804
    pub mbr_0x1808: u8,  // offset: 0x1808
    pub mbr_0x180c: u8,  // offset: 0x180c
}

// Size: 0x1f8 (504 bytes)
#[repr(C)]
pub struct Tank {
    pub cls_0x632100: *const u8,  // offset: 0x0000
}

// Size: 0x1 (1 bytes)
#[repr(C)]
pub struct UIButton {
    _pad_0x0000: [u8; 1],
}

// Size: 0x4fc (1276 bytes)
#[repr(C)]
pub struct UIControl {
    pub cls_0x6313e4: [u8; 1276],  // offset: 0x0000
}

// Size: 0x4fc (1276 bytes)
#[repr(C)]
pub struct UIEditableText {
    pub cls_0x6313e4: [u8; 1276],  // offset: 0x0000
}

// Size: 0xb5 (181 bytes)
#[repr(C)]
pub struct UIElement {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x6: u8,  // offset: 0x0006
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x2c: u8,  // offset: 0x002c
    pub mbr_0x30: u8,  // offset: 0x0030
    pub mbr_0x34: u8,  // offset: 0x0034
    pub mbr_0x38: u8,  // offset: 0x0038
    pub mbr_0x3c: u8,  // offset: 0x003c
    pub mbr_0x40: u8,  // offset: 0x0040
    pub mbr_0x44: u8,  // offset: 0x0044
    pub mbr_0x48: u8,  // offset: 0x0048
    _pad_0x0049: [u8; 3],
    pub mbr_0x4c: u8,  // offset: 0x004c
    pub mbr_0x50: u8,  // offset: 0x0050
    pub mbr_0x54: u8,  // offset: 0x0054
    pub mbr_0x58: u8,  // offset: 0x0058
    pub mbr_0x5c: u8,  // offset: 0x005c
    pub mbr_0x60: u8,  // offset: 0x0060
    pub mbr_0x64: u8,  // offset: 0x0064
    pub mbr_0x68: u8,  // offset: 0x0068
    pub mbr_0x6c: u8,  // offset: 0x006c
    pub mbr_0x70: u8,  // offset: 0x0070
    pub mbr_0x74: u8,  // offset: 0x0074
    pub mbr_0x78: u8,  // offset: 0x0078
    pub mbr_0x7c: u8,  // offset: 0x007c
    pub mbr_0x80: u8,  // offset: 0x0080
    pub mbr_0x84: u8,  // offset: 0x0084
    pub mbr_0x88: u8,  // offset: 0x0088
    pub mbr_0x8c: u8,  // offset: 0x008c
    pub mbr_0x90: u8,  // offset: 0x0090
    pub mbr_0x94: u8,  // offset: 0x0094
    pub mbr_0x98: u8,  // offset: 0x0098
    pub mbr_0x9c: u8,  // offset: 0x009c
    pub mbr_0xa0: u8,  // offset: 0x00a0
    pub mbr_0xa4: u8,  // offset: 0x00a4
    pub mbr_0xa8: u8,  // offset: 0x00a8
    pub mbr_0xac: u8,  // offset: 0x00ac
    pub mbr_0xb0: u8,  // offset: 0x00b0
    pub mbr_0xb1: u8,  // offset: 0x00b1
    pub mbr_0xb2: u8,  // offset: 0x00b2
    pub mbr_0xb3: u8,  // offset: 0x00b3
    pub mbr_0xb4: u8,  // offset: 0x00b4
}

// Size: 0x350 (848 bytes)
#[repr(C)]
pub struct UIImage {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    _pad_0x0004: [u8; 172],
    pub mbr_0xb0: u8,  // offset: 0x00b0
    pub mbr_0xb1: u8,  // offset: 0x00b1
    _pad_0x00b2: [u8; 66],
    pub mbr_0xf4: u8,  // offset: 0x00f4
    _pad_0x00f8: [u8; 124],
    pub mbr_0x174: u8,  // offset: 0x0174
    _pad_0x0178: [u8; 20],
    pub mbr_0x18c: u8,  // offset: 0x018c
    pub mbr_0x190: u8,  // offset: 0x0190
    _pad_0x0194: [u8; 300],
    pub mbr_0x2c0: u8,  // offset: 0x02c0
    _pad_0x02c4: [u8; 138],
    pub mbr_0x34e: u8,  // offset: 0x034e
    pub mbr_0x34f: u8,  // offset: 0x034f
}

// Size: 0xbc (188 bytes)
#[repr(C)]
pub struct UILayout {
    _pad_0x0000: [u8; 184],
    pub mbr_0xb8: u8,  // offset: 0x00b8
}

// Size: 0x4fc (1276 bytes)
#[repr(C)]
pub struct UIListBox {
    pub cls_0x6313e4: [u8; 1276],  // offset: 0x0000
}

// Size: 0x24 (36 bytes)
#[repr(C)]
pub struct UIListBoxItem {
    _pad_0x0000: [u8; 4],
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0008: [u8; 17],
    pub mbr_0x19: u8,  // offset: 0x0019
    _pad_0x001a: [u8; 6],
    pub mbr_0x20: u8,  // offset: 0x0020
}

// Size: 0x1e (30 bytes)
#[repr(C)]
pub struct UIMessage {
    pub mbr_0x0: u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x1d: u8,  // offset: 0x001d
}

// Size: 0x45c (1116 bytes)
#[repr(C)]
pub struct UIMessageQueue {
    pub cls_0x63203c: *const u8,  // offset: 0x0000
    _pad_0x00b5: [u8; 3],
    pub mbr_0xb8: u8,  // offset: 0x00b8
    pub mbr_0xbc: u8,  // offset: 0x00bc
    pub mbr_0xc0: u8,  // offset: 0x00c0
    pub mbr_0xc4: u8,  // offset: 0x00c4
    pub mbr_0xc5: u8,  // offset: 0x00c5
    _pad_0x00c6: [u8; 46],
    pub mbr_0xf4: u8,  // offset: 0x00f4
    _pad_0x00f8: [u8; 148],
    pub mbr_0x18c: u8,  // offset: 0x018c
    pub mbr_0x190: u8,  // offset: 0x0190
    _pad_0x0194: [u8; 8],
    pub mbr_0x19c: u8,  // offset: 0x019c
    _pad_0x01a0: [u8; 4],
    pub mbr_0x1a4: u8,  // offset: 0x01a4
    pub mbr_0x1a8: u8,  // offset: 0x01a8
    pub mbr_0x1ac: u8,  // offset: 0x01ac
    _pad_0x01b0: [u8; 108],
    pub mbr_0x21c: u8,  // offset: 0x021c
    _pad_0x0220: [u8; 20],
    pub mbr_0x234: u8,  // offset: 0x0234
    pub mbr_0x238: u8,  // offset: 0x0238
    pub mbr_0x23c: u8,  // offset: 0x023c
    _pad_0x0240: [u8; 56],
    pub mbr_0x278: u8,  // offset: 0x0278
    pub mbr_0x27c: u8,  // offset: 0x027c
    pub mbr_0x280: u8,  // offset: 0x0280
    _pad_0x0284: [u8; 12],
    pub mbr_0x290: u8,  // offset: 0x0290
    _pad_0x0294: [u8; 12],
    pub mbr_0x2a0: u8,  // offset: 0x02a0
    pub mbr_0x2a4: u8,  // offset: 0x02a4
    pub mbr_0x2a8: u8,  // offset: 0x02a8
    pub mbr_0x2ac: u8,  // offset: 0x02ac
    pub mbr_0x2b0: u8,  // offset: 0x02b0
    pub mbr_0x2b4: u8,  // offset: 0x02b4
    _pad_0x02b8: [u8; 1],
    pub mbr_0x2b9: u8,  // offset: 0x02b9
    _pad_0x02ba: [u8; 6],
    pub mbr_0x2c0: u8,  // offset: 0x02c0
    _pad_0x02c4: [u8; 129],
    pub mbr_0x345: u8,  // offset: 0x0345
    pub mbr_0x349: u8,  // offset: 0x0349
    pub mbr_0x34a: u8,  // offset: 0x034a
    pub mbr_0x34b: u8,  // offset: 0x034b
    pub mbr_0x34f: u8,  // offset: 0x034f
    _pad_0x0350: [u8; 1],
    pub mbr_0x351: u8,  // offset: 0x0351
    _pad_0x0352: [u8; 10],
    pub mbr_0x35c: u8,  // offset: 0x035c
    pub mbr_0x360: u8,  // offset: 0x0360
    pub mbr_0x364: u8,  // offset: 0x0364
    pub mbr_0x368: u8,  // offset: 0x0368
    pub mbr_0x36c: u8,  // offset: 0x036c
    pub mbr_0x370: u8,  // offset: 0x0370
    pub mbr_0x374: u8,  // offset: 0x0374
    pub mbr_0x378: u8,  // offset: 0x0378
    pub mbr_0x37c: u8,  // offset: 0x037c
    pub mbr_0x380: u8,  // offset: 0x0380
    pub mbr_0x384: u8,  // offset: 0x0384
    pub mbr_0x388: u8,  // offset: 0x0388
    _pad_0x038c: [u8; 25],
    pub mbr_0x3a5: u8,  // offset: 0x03a5
    _pad_0x03a6: [u8; 1],
    pub mbr_0x3a7: u8,  // offset: 0x03a7
    _pad_0x03ab: [u8; 1],
    pub mbr_0x3ac: u8,  // offset: 0x03ac
    _pad_0x03ad: [u8; 3],
    pub mbr_0x3b0: u8,  // offset: 0x03b0
    pub mbr_0x3b4: u8,  // offset: 0x03b4
    pub mbr_0x3b8: u8,  // offset: 0x03b8
    pub mbr_0x3bc: u8,  // offset: 0x03bc
    pub mbr_0x3c0: u8,  // offset: 0x03c0
    _pad_0x03c4: [u8; 68],
    pub mbr_0x408: u8,  // offset: 0x0408
    pub mbr_0x40c: u8,  // offset: 0x040c
    pub mbr_0x410: u8,  // offset: 0x0410
    pub mbr_0x414: u8,  // offset: 0x0414
    pub mbr_0x418: u8,  // offset: 0x0418
    pub mbr_0x41c: u8,  // offset: 0x041c
    pub mbr_0x420: u8,  // offset: 0x0420
    pub mbr_0x424: u8,  // offset: 0x0424
    _pad_0x0428: [u8; 20],
    pub mbr_0x43c: u8,  // offset: 0x043c
    pub mbr_0x440: u8,  // offset: 0x0440
    pub mbr_0x444: u8,  // offset: 0x0444
    pub mbr_0x448: u8,  // offset: 0x0448
    pub mbr_0x44c: u8,  // offset: 0x044c
    _pad_0x0450: [u8; 8],
    pub mbr_0x458: u8,  // offset: 0x0458
}

// Size: 0xc4 (196 bytes)
#[repr(C)]
pub struct UIRadioSet {
    _pad_0x0000: [u8; 184],
    pub mbr_0xb8: u8,  // offset: 0x00b8
    _pad_0x00bc: [u8; 4],
    pub mbr_0xc0: u8,  // offset: 0x00c0
}

// Size: 0x4fc (1276 bytes)
#[repr(C)]
pub struct UIScrollBar {
    pub cls_0x6313e4: [u8; 1276],  // offset: 0x0000
}

// Size: 0x3a0 (928 bytes)
#[repr(C)]
pub struct UIScrollingRegion {
    _pad_0x0000: [u8; 64],
    pub mbr_0x40: u8,  // offset: 0x0040
    pub mbr_0x44: u8,  // offset: 0x0044
    _pad_0x0048: [u8; 800],
    pub mbr_0x368: u8,  // offset: 0x0368
    _pad_0x036c: [u8; 8],
    pub mbr_0x374: u8,  // offset: 0x0374
    _pad_0x0378: [u8; 4],
    pub mbr_0x37c: u8,  // offset: 0x037c
    pub mbr_0x380: u8,  // offset: 0x0380
    pub mbr_0x384: u8,  // offset: 0x0384
    _pad_0x0388: [u8; 20],
    pub mbr_0x39c: u8,  // offset: 0x039c
}

// Size: 0x150 (336 bytes)
#[repr(C)]
pub struct ZTAIMgr {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    _pad_0x0004: [u8; 220],
    pub mbr_0xe0: u8,  // offset: 0x00e0
    _pad_0x00e4: [u8; 68],
    pub mbr_0x128: u8,  // offset: 0x0128
    _pad_0x012c: [u8; 12],
    pub mbr_0x138: u8,  // offset: 0x0138
    pub mbr_0x13c: u8,  // offset: 0x013c
    pub mbr_0x140: u8,  // offset: 0x0140
    pub mbr_0x144: u8,  // offset: 0x0144
    pub mbr_0x148: u8,  // offset: 0x0148
    pub mbr_0x14c: u8,  // offset: 0x014c
}

// Size: 0x28 (40 bytes)
#[repr(C)]
pub struct ZTAdvTerrainMgr {
    _pad_0x0000: [u8; 4],
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0005: [u8; 3],
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
}

// Size: 0x160 (352 bytes)
#[repr(C)]
pub struct ZTAmbient {
    pub cls_0x62d5d0: BFOverlay,  // offset: 0x0000
    pub mbr_0x154: u8,  // offset: 0x0154
    pub mbr_0x158: u8,  // offset: 0x0158
    pub mbr_0x15c: u8,  // offset: 0x015c
}

// Size: 0x144 (324 bytes)
#[repr(C)]
pub struct ZTAmbientType {
    pub cls_0x62e58c: BFOverlayType,  // offset: 0x0000
}

// Size: 0x3b8 (952 bytes)
#[repr(C)]
pub struct ZTAnimal {
    pub cls_0x62fa44: ZTUnit,  // offset: 0x0000
    _pad_0x0260: [u8; 300],
    pub food_tile: *const BFTile,  // offset: 0x038c
    _pad_0x0390: [u8; 4],
    pub is_boxed: bool,  // offset: 0x0394
    pub is_egg: bool,  // offset: 0x0395
    _pad_0x0396: [u8; 6],
    pub mbr_0x39c: u8,  // offset: 0x039c
    pub mbr_0x3a0: u8,  // offset: 0x03a0
    pub mbr_0x3a4: i8,  // offset: 0x03a4
    pub mbr_0x3a5: i8,  // offset: 0x03a5
    pub is_dying: bool,  // offset: 0x03a6
    pub mbr_0x3a7: i8,  // offset: 0x03a7
    pub mbr_0x3a8: u8,  // offset: 0x03a8
    pub mbr_0x3ac: u8,  // offset: 0x03ac
    pub mbr_0x3b0: u8,  // offset: 0x03b0
    pub mbr_0x3b4: u8,  // offset: 0x03b4
}

// Size: 0x49c (1180 bytes)
#[repr(C)]
pub struct ZTAnimalType {
    pub cls_0x62e404: ZTUnitType,  // offset: 0x0000
    pub mbr_0x1b0: u8,  // offset: 0x01b0
    pub mbr_0x1b4: u8,  // offset: 0x01b4
    pub mbr_0x1b8: u8,  // offset: 0x01b8
    _pad_0x01bc: [u8; 4],
    pub mbr_0x1c0: u8,  // offset: 0x01c0
    pub mbr_0x1c4: u8,  // offset: 0x01c4
    _pad_0x01c8: [u8; 4],
    pub mbr_0x1cc: u8,  // offset: 0x01cc
    pub mbr_0x1d0: u8,  // offset: 0x01d0
    _pad_0x01d4: [u8; 4],
    pub box_footprint: BFPos,  // offset: 0x01d8
    pub mbr_0x1e4: u8,  // offset: 0x01e4
    pub mbr_0x1e8: u8,  // offset: 0x01e8
    pub mbr_0x1ec: u8,  // offset: 0x01ec
    pub mbr_0x1f0: u8,  // offset: 0x01f0
    pub mbr_0x1f4: u8,  // offset: 0x01f4
    pub mbr_0x1f8: u8,  // offset: 0x01f8
    pub mbr_0x1fc: u8,  // offset: 0x01fc
    pub mbr_0x200: u8,  // offset: 0x0200
    pub mbr_0x204: u8,  // offset: 0x0204
    pub mbr_0x208: u8,  // offset: 0x0208
    pub mbr_0x20c: u8,  // offset: 0x020c
    pub mbr_0x210: u8,  // offset: 0x0210
    pub mbr_0x214: u8,  // offset: 0x0214
    pub mbr_0x218: u8,  // offset: 0x0218
    pub mbr_0x21c: u8,  // offset: 0x021c
    pub mbr_0x220: u8,  // offset: 0x0220
    pub mbr_0x224: u8,  // offset: 0x0224
    pub mbr_0x228: u8,  // offset: 0x0228
    pub mbr_0x22c: u8,  // offset: 0x022c
    pub mbr_0x230: u8,  // offset: 0x0230
    pub mbr_0x234: u8,  // offset: 0x0234
    pub mbr_0x238: u8,  // offset: 0x0238
    pub mbr_0x23c: u8,  // offset: 0x023c
    pub mbr_0x240: u8,  // offset: 0x0240
    pub mbr_0x244: u8,  // offset: 0x0244
    pub mbr_0x248: u8,  // offset: 0x0248
    pub mbr_0x24c: u8,  // offset: 0x024c
    pub mbr_0x250: u8,  // offset: 0x0250
    pub mbr_0x254: u8,  // offset: 0x0254
    pub mbr_0x258: u8,  // offset: 0x0258
    pub mbr_0x25c: u8,  // offset: 0x025c
    pub mbr_0x260: u8,  // offset: 0x0260
    pub mbr_0x264: u8,  // offset: 0x0264
    pub mbr_0x268: u8,  // offset: 0x0268
    pub mbr_0x26c: u8,  // offset: 0x026c
    pub mbr_0x270: u8,  // offset: 0x0270
    pub mbr_0x274: u8,  // offset: 0x0274
    pub mbr_0x278: u8,  // offset: 0x0278
    pub mbr_0x27c: u8,  // offset: 0x027c
    pub mbr_0x280: u8,  // offset: 0x0280
    pub mbr_0x284: u8,  // offset: 0x0284
    pub mbr_0x288: u8,  // offset: 0x0288
    pub mbr_0x28c: u8,  // offset: 0x028c
    pub mbr_0x290: u8,  // offset: 0x0290
    pub mbr_0x294: u8,  // offset: 0x0294
    pub mbr_0x298: u8,  // offset: 0x0298
    pub mbr_0x29c: u8,  // offset: 0x029c
    pub mbr_0x2a0: u8,  // offset: 0x02a0
    _pad_0x02a4: [u8; 8],
    pub mbr_0x2ac: u8,  // offset: 0x02ac
    pub mbr_0x2b0: u8,  // offset: 0x02b0
    _pad_0x02b4: [u8; 8],
    pub mbr_0x2bc: u8,  // offset: 0x02bc
    pub cls_0x40b585: [u8; 92],  // offset: 0x02c0
    _pad_0x031c: [u8; 24],
    pub mbr_0x334: u8,  // offset: 0x0334
    pub mbr_0x338: u8,  // offset: 0x0338
    pub mbr_0x33c: u8,  // offset: 0x033c
    pub mbr_0x340: u8,  // offset: 0x0340
    pub mbr_0x344: u8,  // offset: 0x0344
    pub mbr_0x348: u8,  // offset: 0x0348
    pub mbr_0x34c: u8,  // offset: 0x034c
    pub mbr_0x350: u8,  // offset: 0x0350
    pub mbr_0x354: u8,  // offset: 0x0354
    pub mbr_0x358: u8,  // offset: 0x0358
    pub mbr_0x35c: u8,  // offset: 0x035c
    pub mbr_0x360: u8,  // offset: 0x0360
    pub mbr_0x364: u8,  // offset: 0x0364
    pub mbr_0x368: u8,  // offset: 0x0368
    pub mbr_0x36c: u8,  // offset: 0x036c
    _pad_0x0370: [u8; 8],
    pub mbr_0x378: u8,  // offset: 0x0378
    pub mbr_0x37c: u8,  // offset: 0x037c
    pub mbr_0x380: u8,  // offset: 0x0380
    pub c_time_death: u8,  // offset: 0x0384
    pub mbr_0x388: u8,  // offset: 0x0388
    pub mbr_0x38c: u8,  // offset: 0x038c
    pub mbr_0x390: u8,  // offset: 0x0390
    pub mbr_0x394: u8,  // offset: 0x0394
    pub mbr_0x398: u8,  // offset: 0x0398
    pub mbr_0x39c: u8,  // offset: 0x039c
    pub mbr_0x3a0: u8,  // offset: 0x03a0
    pub mbr_0x3a4: u8,  // offset: 0x03a4
    pub mbr_0x3a8: u8,  // offset: 0x03a8
    pub mbr_0x3ac: u8,  // offset: 0x03ac
    pub mbr_0x3b0: u8,  // offset: 0x03b0
    pub mbr_0x3b4: u8,  // offset: 0x03b4
    pub mbr_0x3b8: u8,  // offset: 0x03b8
    pub mbr_0x3bc: u8,  // offset: 0x03bc
    pub mbr_0x3c0: u8,  // offset: 0x03c0
    pub mbr_0x3c4: u8,  // offset: 0x03c4
    pub mbr_0x3c8: u8,  // offset: 0x03c8
    pub mbr_0x3cc: u8,  // offset: 0x03cc
    pub mbr_0x3cd: u8,  // offset: 0x03cd
    pub mbr_0x3ce: u8,  // offset: 0x03ce
    pub mbr_0x3cf: u8,  // offset: 0x03cf
    pub mbr_0x3d0: u8,  // offset: 0x03d0
    pub mbr_0x3d1: u8,  // offset: 0x03d1
    pub mbr_0x3d2: u8,  // offset: 0x03d2
    pub mbr_0x3d3: u8,  // offset: 0x03d3
    pub mbr_0x3d4: u8,  // offset: 0x03d4
    pub mbr_0x3d5: u8,  // offset: 0x03d5
    pub mbr_0x3d6: u8,  // offset: 0x03d6
    pub mbr_0x3d7: u8,  // offset: 0x03d7
    pub mbr_0x3d8: u8,  // offset: 0x03d8
    _pad_0x03d9: [u8; 3],
    pub mbr_0x3dc: u8,  // offset: 0x03dc
    pub mbr_0x3e0: u8,  // offset: 0x03e0
    pub mbr_0x3e4: u8,  // offset: 0x03e4
    pub mbr_0x3e8: u8,  // offset: 0x03e8
    pub mbr_0x3ec: u8,  // offset: 0x03ec
    pub mbr_0x3f0: u8,  // offset: 0x03f0
    pub mbr_0x3f4: u8,  // offset: 0x03f4
    pub mbr_0x3f8: u8,  // offset: 0x03f8
    pub mbr_0x3fc: u8,  // offset: 0x03fc
    pub mbr_0x400: u8,  // offset: 0x0400
    pub mbr_0x404: u8,  // offset: 0x0404
    pub mbr_0x405: u8,  // offset: 0x0405
    _pad_0x0406: [u8; 2],
    pub mbr_0x408: u8,  // offset: 0x0408
    pub mbr_0x40c: u8,  // offset: 0x040c
    pub egg_footprint: BFPos,  // offset: 0x0410
    pub mbr_0x41c: u8,  // offset: 0x041c
    pub mbr_0x420: u8,  // offset: 0x0420
    pub mbr_0x424: u8,  // offset: 0x0424
    pub mbr_0x428: u8,  // offset: 0x0428
    pub mbr_0x42c: u8,  // offset: 0x042c
    pub mbr_0x430: u8,  // offset: 0x0430
    pub mbr_0x434: u8,  // offset: 0x0434
    pub mbr_0x438: u8,  // offset: 0x0438
    pub mbr_0x43c: u8,  // offset: 0x043c
    pub mbr_0x440: u8,  // offset: 0x0440
    pub mbr_0x444: u8,  // offset: 0x0444
    pub mbr_0x448: u8,  // offset: 0x0448
    pub mbr_0x44c: u8,  // offset: 0x044c
    pub mbr_0x44d: u8,  // offset: 0x044d
    _pad_0x044e: [u8; 2],
    pub mbr_0x450: u8,  // offset: 0x0450
    pub mbr_0x454: u8,  // offset: 0x0454
    _pad_0x0458: [u8; 4],
    pub mbr_0x45c: u8,  // offset: 0x045c
    pub mbr_0x460: u8,  // offset: 0x0460
    _pad_0x0464: [u8; 4],
    pub mbr_0x468: u8,  // offset: 0x0468
    pub mbr_0x46c: u8,  // offset: 0x046c
    _pad_0x0470: [u8; 4],
    pub mbr_0x474: u8,  // offset: 0x0474
    pub mbr_0x478: u8,  // offset: 0x0478
    pub mbr_0x47c: u8,  // offset: 0x047c
    _pad_0x0480: [u8; 4],
    pub mbr_0x484: u8,  // offset: 0x0484
    pub mbr_0x488: u8,  // offset: 0x0488
    pub mbr_0x48c: u8,  // offset: 0x048c
    pub mbr_0x490: u8,  // offset: 0x0490
    pub mbr_0x494: u8,  // offset: 0x0494
    pub mbr_0x498: u8,  // offset: 0x0498
}

// Size: 0x514 (1300 bytes)
#[repr(C)]
pub struct ZTApp {
    _pad_0x0000: [u8; 4],
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x6: u8,  // offset: 0x0006
    pub mbr_0x8: u8,  // offset: 0x0008
    _pad_0x000c: [u8; 4],
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x29: u8,  // offset: 0x0029
    _pad_0x002d: [u8; 508],
    pub mbr_0x229: u8,  // offset: 0x0229
    _pad_0x022d: [u8; 511],
    pub mbr_0x42c: u8,  // offset: 0x042c
    pub mbr_0x430: u8,  // offset: 0x0430
    pub mbr_0x434: u8,  // offset: 0x0434
    pub mbr_0x438: u8,  // offset: 0x0438
    pub mbr_0x43c: u8,  // offset: 0x043c
    pub mbr_0x440: u8,  // offset: 0x0440
    pub mbr_0x441: u8,  // offset: 0x0441
    pub mbr_0x442: u8,  // offset: 0x0442
    _pad_0x0443: [u8; 1],
    pub mbr_0x444: u8,  // offset: 0x0444
    pub mbr_0x446: u8,  // offset: 0x0446
    _pad_0x0447: [u8; 1],
    pub mbr_0x448: u8,  // offset: 0x0448
    pub mbr_0x44c: u8,  // offset: 0x044c
    pub mbr_0x450: u8,  // offset: 0x0450
    pub mbr_0x454: u8,  // offset: 0x0454
    pub mbr_0x458: u8,  // offset: 0x0458
    pub mbr_0x45c: u8,  // offset: 0x045c
    pub mbr_0x460: u8,  // offset: 0x0460
    _pad_0x0464: [u8; 64],
    pub mbr_0x4a4: u8,  // offset: 0x04a4
    pub mbr_0x4a5: u8,  // offset: 0x04a5
    _pad_0x04a6: [u8; 2],
    pub mbr_0x4a8: u8,  // offset: 0x04a8
    pub mbr_0x4ac: u8,  // offset: 0x04ac
    pub mbr_0x4b0: u8,  // offset: 0x04b0
    pub mbr_0x4b4: u8,  // offset: 0x04b4
    pub mbr_0x4b8: u8,  // offset: 0x04b8
    pub mbr_0x4bc: u8,  // offset: 0x04bc
    pub mbr_0x4c0: u8,  // offset: 0x04c0
    pub mbr_0x4c4: u8,  // offset: 0x04c4
    pub mbr_0x4c8: u8,  // offset: 0x04c8
    pub mbr_0x4cc: u8,  // offset: 0x04cc
    pub mbr_0x4d0: u8,  // offset: 0x04d0
    _pad_0x04d1: [u8; 3],
    pub mbr_0x4d4: u8,  // offset: 0x04d4
    pub mbr_0x4d8: u8,  // offset: 0x04d8
    pub mbr_0x4dc: u8,  // offset: 0x04dc
    _pad_0x04e0: [u8; 12],
    pub mbr_0x4ec: u8,  // offset: 0x04ec
    pub mbr_0x4f0: u8,  // offset: 0x04f0
    pub mbr_0x4f4: u8,  // offset: 0x04f4
    pub mbr_0x4f8: u8,  // offset: 0x04f8
    pub mbr_0x4fc: u8,  // offset: 0x04fc
    pub mbr_0x500: u8,  // offset: 0x0500
    pub mbr_0x504: u8,  // offset: 0x0504
    pub mbr_0x508: u8,  // offset: 0x0508
    pub mbr_0x509: u8,  // offset: 0x0509
    _pad_0x050a: [u8; 2],
    pub mbr_0x50c: u8,  // offset: 0x050c
    pub mbr_0x510: u8,  // offset: 0x0510
}

// Size: 0x8 (8 bytes)
#[repr(C)]
pub struct ZTAwardMgr {
    pub mbr_0x0: u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
}

// Size: 0x3b8 (952 bytes)
#[repr(C)]
pub struct ZTBuilding {
    pub cls_0x62d950: ZTScenery,  // offset: 0x0000
    pub mbr_0x158: u8,  // offset: 0x0158
    pub mbr_0x15c: u8,  // offset: 0x015c
    pub mbr_0x160: u8,  // offset: 0x0160
    pub mbr_0x164: u8,  // offset: 0x0164
    pub mbr_0x168: u8,  // offset: 0x0168
    pub mbr_0x16c: u8,  // offset: 0x016c
    pub mbr_0x170: u8,  // offset: 0x0170
    pub mbr_0x174: u8,  // offset: 0x0174
    pub mbr_0x178: u8,  // offset: 0x0178
    _pad_0x017c: [u8; 4],
    pub mbr_0x180: u8,  // offset: 0x0180
    pub mbr_0x184: u8,  // offset: 0x0184
    pub mbr_0x188: u8,  // offset: 0x0188
    pub mbr_0x18c: u8,  // offset: 0x018c
    pub mbr_0x190: u8,  // offset: 0x0190
    pub mbr_0x194: u8,  // offset: 0x0194
    pub mbr_0x198: u8,  // offset: 0x0198
    pub mbr_0x19c: u8,  // offset: 0x019c
    pub mbr_0x1a0: u8,  // offset: 0x01a0
    pub mbr_0x1a4: u8,  // offset: 0x01a4
    pub mbr_0x1a8: u8,  // offset: 0x01a8
    pub mbr_0x1ac: u8,  // offset: 0x01ac
    pub mbr_0x1b0: u8,  // offset: 0x01b0
    pub mbr_0x1b4: u8,  // offset: 0x01b4
    pub mbr_0x1b8: u8,  // offset: 0x01b8
    pub mbr_0x1bc: u8,  // offset: 0x01bc
    pub mbr_0x1c0: u8,  // offset: 0x01c0
    pub mbr_0x1c4: u8,  // offset: 0x01c4
    _pad_0x01c6: [u8; 2],
    pub mbr_0x1c8: u8,  // offset: 0x01c8
    _pad_0x01cc: [u8; 65],
    pub mbr_0x20d: u8,  // offset: 0x020d
    _pad_0x020e: [u8; 6],
    pub mbr_0x214: u8,  // offset: 0x0214
    pub mbr_0x218: u8,  // offset: 0x0218
    pub mbr_0x21c: u8,  // offset: 0x021c
    _pad_0x0220: [u8; 20],
    pub mbr_0x234: u8,  // offset: 0x0234
    _pad_0x0238: [u8; 12],
    pub mbr_0x244: u8,  // offset: 0x0244
    _pad_0x0248: [u8; 4],
    pub mbr_0x24c: u8,  // offset: 0x024c
    pub mbr_0x24d: u8,  // offset: 0x024d
    pub mbr_0x24e: u8,  // offset: 0x024e
    _pad_0x024f: [u8; 9],
    pub mbr_0x258: u8,  // offset: 0x0258
    pub mbr_0x25c: u8,  // offset: 0x025c
    _pad_0x025d: [u8; 3],
    pub mbr_0x260: u8,  // offset: 0x0260
    pub mbr_0x264: u8,  // offset: 0x0264
    _pad_0x0268: [u8; 4],
    pub mbr_0x26c: u8,  // offset: 0x026c
    _pad_0x0270: [u8; 40],
    pub mbr_0x298: u8,  // offset: 0x0298
    pub mbr_0x29c: u8,  // offset: 0x029c
    pub mbr_0x2a0: u8,  // offset: 0x02a0
    pub mbr_0x2a4: u8,  // offset: 0x02a4
    pub mbr_0x2a8: u8,  // offset: 0x02a8
    pub mbr_0x2ac: u8,  // offset: 0x02ac
    pub mbr_0x2b0: u8,  // offset: 0x02b0
    _pad_0x02b4: [u8; 4],
    pub mbr_0x2b8: u8,  // offset: 0x02b8
    pub mbr_0x2bc: u8,  // offset: 0x02bc
    pub mbr_0x2c0: u8,  // offset: 0x02c0
    _pad_0x02c4: [u8; 56],
    pub mbr_0x2fc: u8,  // offset: 0x02fc
    _pad_0x0300: [u8; 12],
    pub mbr_0x30c: u8,  // offset: 0x030c
    _pad_0x0310: [u8; 4],
    pub mbr_0x314: u8,  // offset: 0x0314
    _pad_0x0318: [u8; 16],
    pub mbr_0x328: u8,  // offset: 0x0328
    pub mbr_0x32c: u8,  // offset: 0x032c
    _pad_0x0330: [u8; 9],
    pub mbr_0x339: u8,  // offset: 0x0339
    _pad_0x033a: [u8; 2],
    pub mbr_0x33c: u8,  // offset: 0x033c
    pub mbr_0x33d: u8,  // offset: 0x033d
    pub mbr_0x33e: u8,  // offset: 0x033e
    _pad_0x033f: [u8; 5],
    pub mbr_0x344: u8,  // offset: 0x0344
    _pad_0x0348: [u8; 24],
    pub mbr_0x360: u8,  // offset: 0x0360
    pub mbr_0x364: u8,  // offset: 0x0364
    _pad_0x0368: [u8; 16],
    pub mbr_0x378: u8,  // offset: 0x0378
    _pad_0x037c: [u8; 4],
    pub mbr_0x380: u8,  // offset: 0x0380
    _pad_0x0384: [u8; 8],
    pub mbr_0x38c: u8,  // offset: 0x038c
    _pad_0x0390: [u8; 3],
    pub mbr_0x393: u8,  // offset: 0x0393
    _pad_0x0394: [u8; 1],
    pub mbr_0x395: u8,  // offset: 0x0395
    _pad_0x0396: [u8; 2],
    pub mbr_0x398: u8,  // offset: 0x0398
    pub mbr_0x39c: u8,  // offset: 0x039c
    _pad_0x039d: [u8; 1],
    pub mbr_0x39e: u8,  // offset: 0x039e
    _pad_0x039f: [u8; 2],
    pub mbr_0x3a1: u8,  // offset: 0x03a1
    pub mbr_0x3a2: u8,  // offset: 0x03a2
    pub mbr_0x3a3: u8,  // offset: 0x03a3
    pub mbr_0x3a4: u8,  // offset: 0x03a4
    pub mbr_0x3a5: u8,  // offset: 0x03a5
    pub mbr_0x3a6: u8,  // offset: 0x03a6
    _pad_0x03a7: [u8; 2],
    pub mbr_0x3a9: u8,  // offset: 0x03a9
    pub mbr_0x3aa: u8,  // offset: 0x03aa
    _pad_0x03ab: [u8; 1],
    pub mbr_0x3ac: u8,  // offset: 0x03ac
    _pad_0x03b0: [u8; 4],
    pub mbr_0x3b4: u8,  // offset: 0x03b4
}

// Size: 0x20 (32 bytes)
#[repr(C)]
pub struct ZTBuilding_Slot {
    _pad_0x0000: [u8; 24],
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
}

// Size: 0x23c (572 bytes)
#[repr(C)]
pub struct ZTBuildingType {
    pub cls_0x6303f4: ZTSceneryType,  // offset: 0x0000
    pub cls_0x4bbec4: [u8; 4],  // offset: 0x0168
    _pad_0x016c: [u8; 64],
    pub mbr_0x1ac: u8,  // offset: 0x01ac
    pub mbr_0x1b0: u8,  // offset: 0x01b0
    pub mbr_0x1b4: u8,  // offset: 0x01b4
    _pad_0x01b8: [u8; 24],
    pub mbr_0x1d0: u8,  // offset: 0x01d0
    pub mbr_0x1d4: u8,  // offset: 0x01d4
    _pad_0x01d8: [u8; 4],
    pub mbr_0x1dc: u8,  // offset: 0x01dc
    pub mbr_0x1e0: u8,  // offset: 0x01e0
    _pad_0x01e4: [u8; 12],
    pub mbr_0x1f0: u8,  // offset: 0x01f0
    pub mbr_0x1f4: u8,  // offset: 0x01f4
    _pad_0x01f8: [u8; 8],
    pub mbr_0x200: u8,  // offset: 0x0200
    pub mbr_0x204: u8,  // offset: 0x0204
    pub mbr_0x208: u8,  // offset: 0x0208
    pub mbr_0x20c: u8,  // offset: 0x020c
    pub mbr_0x210: u8,  // offset: 0x0210
    pub mbr_0x214: u8,  // offset: 0x0214
    pub mbr_0x218: u8,  // offset: 0x0218
    pub mbr_0x21c: u8,  // offset: 0x021c
    pub mbr_0x220: u8,  // offset: 0x0220
    pub mbr_0x224: u8,  // offset: 0x0224
    pub mbr_0x228: u8,  // offset: 0x0228
    pub mbr_0x22c: u8,  // offset: 0x022c
    pub mbr_0x230: u8,  // offset: 0x0230
    pub mbr_0x234: u8,  // offset: 0x0234
    pub mbr_0x238: u8,  // offset: 0x0238
}

// Size: 0x178 (376 bytes)
#[repr(C)]
pub struct ZTFence {
    pub cls_0x62d950: ZTScenery,  // offset: 0x0000
    pub mbr_0x158: u8,  // offset: 0x0158
    pub mbr_0x159: u8,  // offset: 0x0159
    _pad_0x015a: [u8; 2],
    pub mbr_0x15c: u8,  // offset: 0x015c
    pub mbr_0x160: u8,  // offset: 0x0160
    pub mbr_0x164: u8,  // offset: 0x0164
    _pad_0x0165: [u8; 3],
    pub mbr_0x168: u8,  // offset: 0x0168
    pub mbr_0x16c: u8,  // offset: 0x016c
    pub mbr_0x170: u8,  // offset: 0x0170
    pub mbr_0x174: u8,  // offset: 0x0174
    _pad_0x0175: [u8; 3],
}

// Size: 0x1a4 (420 bytes)
#[repr(C)]
pub struct ZTFenceType {
    pub cls_0x6303f4: ZTSceneryType,  // offset: 0x0000
    pub mbr_0x168: u8,  // offset: 0x0168
    pub mbr_0x16c: u8,  // offset: 0x016c
    pub mbr_0x170: u8,  // offset: 0x0170
    pub mbr_0x174: u8,  // offset: 0x0174
    pub mbr_0x178: u8,  // offset: 0x0178
    pub mbr_0x17c: u8,  // offset: 0x017c
    pub mbr_0x180: u8,  // offset: 0x0180
    pub mbr_0x184: u8,  // offset: 0x0184
    pub mbr_0x188: u8,  // offset: 0x0188
    pub mbr_0x18c: u8,  // offset: 0x018c
    pub mbr_0x190: u8,  // offset: 0x0190
    pub mbr_0x191: u8,  // offset: 0x0191
    pub mbr_0x192: u8,  // offset: 0x0192
    pub mbr_0x193: u8,  // offset: 0x0193
    pub mbr_0x194: u8,  // offset: 0x0194
    pub mbr_0x195: u8,  // offset: 0x0195
    pub mbr_0x196: u8,  // offset: 0x0196
    pub mbr_0x197: u8,  // offset: 0x0197
    pub mbr_0x198: u8,  // offset: 0x0198
    pub mbr_0x199: u8,  // offset: 0x0199
    _pad_0x019a: [u8; 2],
    pub mbr_0x19c: u8,  // offset: 0x019c
    pub mbr_0x1a0: u8,  // offset: 0x01a0
}

// Size: 0x158 (344 bytes)
#[repr(C)]
pub struct ZTFood {
    pub cls_0x62d950: ZTScenery,  // offset: 0x0000
}

// Size: 0x16c (364 bytes)
#[repr(C)]
pub struct ZTFoodType {
    pub cls_0x6303f4: ZTSceneryType,  // offset: 0x0000
    pub mbr_0x168: u8,  // offset: 0x0168
}

// Size: 0xc (12 bytes)
#[repr(C)]
pub struct ZTGameMgr {
    _pad_0x0000: [u8; 4],
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0005: [u8; 3],
    pub mbr_0x8: u8,  // offset: 0x0008
}

// Size: 0x1a (26 bytes)
#[repr(C)]
pub struct ZTGoalAvoid {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    _pad_0x0011: [u8; 3],
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x19: u8,  // offset: 0x0019
}

// Size: 0x18 (24 bytes)
#[repr(C)]
pub struct ZTGoalFixFilter {
    pub cls_0x63244c: *const u8,  // offset: 0x0000
    _pad_0x0011: [u8; 3],
    pub mbr_0x14: u8,  // offset: 0x0014
}

// Size: 0x19 (25 bytes)
#[repr(C)]
pub struct ZTGoalHabitatDuties {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    _pad_0x0011: [u8; 3],
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
}

// Size: 0x18 (24 bytes)
#[repr(C)]
pub struct ZTGoalHeliReturn {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    _pad_0x0011: [u8; 3],
    pub mbr_0x14: u8,  // offset: 0x0014
}

// Size: 0x18 (24 bytes)
#[repr(C)]
pub struct ZTGoalLeave {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    _pad_0x0011: [u8; 3],
    pub mbr_0x14: u8,  // offset: 0x0014
}

// Size: 0x18 (24 bytes)
#[repr(C)]
pub struct ZTGoalSite {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    _pad_0x0011: [u8; 3],
    pub mbr_0x14: u8,  // offset: 0x0014
}

// Size: 0x39c (924 bytes)
#[repr(C)]
pub struct ZTGuest {
    pub cls_0x62fa44: ZTUnit,  // offset: 0x0000
    _pad_0x0260: [u8; 316],
}

// Size: 0x2e8 (744 bytes)
#[repr(C)]
pub struct ZTGuestType {
    pub cls_0x62e404: ZTUnitType,  // offset: 0x0000
    _pad_0x01b0: [u8; 4],
    pub mbr_0x1b4: u8,  // offset: 0x01b4
    pub mbr_0x1b8: u8,  // offset: 0x01b8
    pub mbr_0x1bc: u8,  // offset: 0x01bc
    pub mbr_0x1c0: u8,  // offset: 0x01c0
    pub mbr_0x1c4: u8,  // offset: 0x01c4
    pub mbr_0x1c8: u8,  // offset: 0x01c8
    pub mbr_0x1cc: u8,  // offset: 0x01cc
    pub mbr_0x1d0: u8,  // offset: 0x01d0
    pub mbr_0x1d4: u8,  // offset: 0x01d4
    pub mbr_0x1d8: u8,  // offset: 0x01d8
    pub mbr_0x1dc: u8,  // offset: 0x01dc
    pub mbr_0x1e0: u8,  // offset: 0x01e0
    pub mbr_0x1e4: u8,  // offset: 0x01e4
    pub mbr_0x1e8: u8,  // offset: 0x01e8
    pub mbr_0x1ec: u8,  // offset: 0x01ec
    pub mbr_0x1f0: u8,  // offset: 0x01f0
    pub mbr_0x1f4: u8,  // offset: 0x01f4
    pub mbr_0x1f8: u8,  // offset: 0x01f8
    pub mbr_0x1fc: u8,  // offset: 0x01fc
    pub mbr_0x200: u8,  // offset: 0x0200
    pub mbr_0x204: u8,  // offset: 0x0204
    pub mbr_0x208: u8,  // offset: 0x0208
    pub mbr_0x20c: u8,  // offset: 0x020c
    pub mbr_0x210: u8,  // offset: 0x0210
    pub mbr_0x214: u8,  // offset: 0x0214
    pub mbr_0x218: u8,  // offset: 0x0218
    pub mbr_0x21c: u8,  // offset: 0x021c
    pub mbr_0x220: u8,  // offset: 0x0220
    pub mbr_0x224: u8,  // offset: 0x0224
    pub mbr_0x228: u8,  // offset: 0x0228
    pub mbr_0x22c: u8,  // offset: 0x022c
    pub mbr_0x230: u8,  // offset: 0x0230
    pub mbr_0x234: u8,  // offset: 0x0234
    pub mbr_0x238: u8,  // offset: 0x0238
    pub mbr_0x23c: u8,  // offset: 0x023c
    pub mbr_0x240: u8,  // offset: 0x0240
    pub mbr_0x244: u8,  // offset: 0x0244
    pub mbr_0x248: u8,  // offset: 0x0248
    pub mbr_0x24c: u8,  // offset: 0x024c
    pub mbr_0x250: u8,  // offset: 0x0250
    pub mbr_0x254: u8,  // offset: 0x0254
    pub mbr_0x258: u8,  // offset: 0x0258
    pub mbr_0x25c: u8,  // offset: 0x025c
    pub mbr_0x260: u8,  // offset: 0x0260
    pub mbr_0x264: u8,  // offset: 0x0264
    pub mbr_0x268: u8,  // offset: 0x0268
    pub mbr_0x26c: u8,  // offset: 0x026c
    pub mbr_0x270: u8,  // offset: 0x0270
    pub mbr_0x274: u8,  // offset: 0x0274
    pub mbr_0x278: u8,  // offset: 0x0278
    pub mbr_0x27c: u8,  // offset: 0x027c
    pub mbr_0x280: u8,  // offset: 0x0280
    pub mbr_0x284: u8,  // offset: 0x0284
    pub mbr_0x288: u8,  // offset: 0x0288
    pub mbr_0x28c: u8,  // offset: 0x028c
    pub mbr_0x290: u8,  // offset: 0x0290
    pub mbr_0x294: u8,  // offset: 0x0294
    pub mbr_0x298: u8,  // offset: 0x0298
    pub mbr_0x29c: u8,  // offset: 0x029c
    pub mbr_0x2a0: u8,  // offset: 0x02a0
    pub mbr_0x2a4: u8,  // offset: 0x02a4
    pub mbr_0x2a8: u8,  // offset: 0x02a8
    pub mbr_0x2ac: u8,  // offset: 0x02ac
    pub mbr_0x2b0: u8,  // offset: 0x02b0
    pub mbr_0x2b4: u8,  // offset: 0x02b4
    pub mbr_0x2b8: u8,  // offset: 0x02b8
    pub mbr_0x2bc: u8,  // offset: 0x02bc
    pub mbr_0x2c0: u8,  // offset: 0x02c0
    pub mbr_0x2c4: u8,  // offset: 0x02c4
    pub mbr_0x2c8: u8,  // offset: 0x02c8
    pub mbr_0x2cc: u8,  // offset: 0x02cc
    pub mbr_0x2d0: u8,  // offset: 0x02d0
    pub mbr_0x2d4: u8,  // offset: 0x02d4
    pub mbr_0x2d8: u8,  // offset: 0x02d8
    pub mbr_0x2dc: u8,  // offset: 0x02dc
    pub mbr_0x2e0: u8,  // offset: 0x02e0
    pub mbr_0x2e4: u8,  // offset: 0x02e4
}

// Size: 0x3a5 (933 bytes)
#[repr(C)]
pub struct ZTGuide {
    pub cls_0x62ed84: ZTStaff,  // offset: 0x0000
    _pad_0x039c: [u8; 7],
    pub mbr_0x3a3: u8,  // offset: 0x03a3
    pub mbr_0x3a4: u8,  // offset: 0x03a4
}

// Size: 0x20c (524 bytes)
#[repr(C)]
pub struct ZTGuideType {
    pub cls_0x62e630: ZTStaffType,  // offset: 0x0000
    _pad_0x01f2: [u8; 2],
    pub mbr_0x1f4: u8,  // offset: 0x01f4
    pub mbr_0x1f8: u8,  // offset: 0x01f8
    pub mbr_0x1fc: u8,  // offset: 0x01fc
    pub mbr_0x200: u8,  // offset: 0x0200
    pub mbr_0x204: u8,  // offset: 0x0204
    pub mbr_0x208: u8,  // offset: 0x0208
}

// Size: 0x1f8 (504 bytes)
#[repr(C)]
pub struct ZTHabitat {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0008: [u8; 8],
    pub zoo_entrance_x: i32,  // offset: 0x0010
    pub zoo_entrance_y: i32,  // offset: 0x0014
    _pad_0x0018: [u8; 120],
    pub entrance_rotation: i32,  // offset: 0x0090
    _pad_0x0094: [u8; 88],
    pub mbr_0xec: u8,  // offset: 0x00ec
    _pad_0x00f0: [u8; 4],
    pub mbr_0xf4: u8,  // offset: 0x00f4
    pub mbr_0xf8: u8,  // offset: 0x00f8
    pub current_donations: u8,  // offset: 0x00fc
    pub last_donations: u8,  // offset: 0x0100
    pub total_donations: u8,  // offset: 0x0104
    pub current_upkeep: u8,  // offset: 0x0108
    pub last_upkeep: u8,  // offset: 0x010c
    pub total_upkeep: u8,  // offset: 0x0110
    pub mbr_0x114: u8,  // offset: 0x0114
    pub mbr_0x118: u8,  // offset: 0x0118
    pub mbr_0x11c: u8,  // offset: 0x011c
    pub created_timestamp: u8,  // offset: 0x0120
    pub mbr_0x124: u8,  // offset: 0x0124
    pub mbr_0x128: u8,  // offset: 0x0128
    pub mbr_0x12c: u8,  // offset: 0x012c
    _pad_0x0130: [u8; 2],
    pub mbr_0x132: u8,  // offset: 0x0132
    _pad_0x0133: [u8; 1],
    pub mbr_0x134: u8,  // offset: 0x0134
    _pad_0x0138: [u8; 4],
    pub mbr_0x13c: u8,  // offset: 0x013c
    pub mbr_0x140: u8,  // offset: 0x0140
    pub mbr_0x144: u8,  // offset: 0x0144
    _pad_0x0148: [u8; 176],
}

// Size: 0x70 (112 bytes)
#[repr(C)]
pub struct ZTHabitatMgr {
    pub mbr_0x0: u32,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0005: [u8; 3],
    pub map_size_x: i32,  // offset: 0x0008
    pub map_size_y: i32,  // offset: 0x000c
    pub zoo_entrance_x: i32,  // offset: 0x0010
    pub zoo_entrance_y: i32,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub exhibit_array_start: u8,  // offset: 0x001c
    pub exhibit_array_end: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x2c: u8,  // offset: 0x002c
    pub mbr_0x30: u8,  // offset: 0x0030
    pub mbr_0x34: u8,  // offset: 0x0034
    pub mbr_0x38: u8,  // offset: 0x0038
    pub mbr_0x3c: u8,  // offset: 0x003c
    pub mbr_0x40: u8,  // offset: 0x0040
    pub mbr_0x44: u8,  // offset: 0x0044
    pub mbr_0x48: u8,  // offset: 0x0048
    pub mbr_0x4c: u8,  // offset: 0x004c
    pub mbr_0x50: u8,  // offset: 0x0050
    pub mbr_0x54: u8,  // offset: 0x0054
    pub mbr_0x58: u8,  // offset: 0x0058
    pub mbr_0x5c: u8,  // offset: 0x005c
    pub mbr_0x60: u8,  // offset: 0x0060
    _pad_0x0064: [u8; 12],
}

// Size: 0x39c (924 bytes)
#[repr(C)]
pub struct ZTHelicopter {
    pub cls_0x62ed84: ZTStaff,  // offset: 0x0000
}

// Size: 0x1fc (508 bytes)
#[repr(C)]
pub struct ZTHelicopterType {
    pub cls_0x62e630: ZTStaffType,  // offset: 0x0000
    _pad_0x01f2: [u8; 2],
    pub mbr_0x1f4: u8,  // offset: 0x01f4
    pub mbr_0x1f8: u8,  // offset: 0x01f8
}

// Size: 0x39c (924 bytes)
#[repr(C)]
pub struct ZTKeeper {
    pub cls_0x62ed84: ZTStaff,  // offset: 0x0000
}

// Size: 0x218 (536 bytes)
#[repr(C)]
pub struct ZTKeeperType {
    pub cls_0x62e630: ZTStaffType,  // offset: 0x0000
    _pad_0x01f2: [u8; 2],
    pub mbr_0x1f4: u8,  // offset: 0x01f4
    pub mbr_0x1f8: u8,  // offset: 0x01f8
    pub mbr_0x1fc: u8,  // offset: 0x01fc
    pub mbr_0x200: u8,  // offset: 0x0200
    pub mbr_0x204: u8,  // offset: 0x0204
    pub mbr_0x208: u8,  // offset: 0x0208
    pub mbr_0x20c: u8,  // offset: 0x020c
    pub mbr_0x210: u8,  // offset: 0x0210
    pub mbr_0x214: u8,  // offset: 0x0214
}

// Size: 0x39c (924 bytes)
#[repr(C)]
pub struct ZTMaint {
    pub cls_0x62ed84: ZTStaff,  // offset: 0x0000
}

// Size: 0x214 (532 bytes)
#[repr(C)]
pub struct ZTMaintType {
    pub cls_0x62e630: ZTStaffType,  // offset: 0x0000
    _pad_0x01f2: [u8; 2],
    pub mbr_0x1f4: u8,  // offset: 0x01f4
    pub mbr_0x1f8: u8,  // offset: 0x01f8
    pub mbr_0x1fc: u8,  // offset: 0x01fc
    pub mbr_0x200: u8,  // offset: 0x0200
    pub mbr_0x204: u8,  // offset: 0x0204
    pub mbr_0x208: u8,  // offset: 0x0208
    pub mbr_0x20c: u8,  // offset: 0x020c
    pub mbr_0x210: u8,  // offset: 0x0210
}

// Size: 0x5e9 (1513 bytes)
#[repr(C)]
pub struct ZTMapView {
    pub cls_0x6314c8: [u8; 1488],  // offset: 0x0000
    _pad_0x05d0: [u8; 25],
}

// Size: 0x10 (16 bytes)
#[repr(C)]
pub struct ZTMarketingMgr {
    _pad_0x0000: [u8; 4],
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0005: [u8; 3],
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
}

// Size: 0x24 (36 bytes)
#[repr(C)]
pub struct ZTMegatileMgr {
    _pad_0x0000: [u8; 4],
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0005: [u8; 19],
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
}

// Size: 0x4fc (1276 bytes)
#[repr(C)]
pub struct ZTMessageQueue {
    pub cls_0x631b04: [u8; 1276],  // offset: 0x0000
}

// Size: 0x4fc (1276 bytes)
#[repr(C)]
pub struct ZTMiniMap {
    pub cls_0x63203c: *const u8,  // offset: 0x0000
    _pad_0x00b5: [u8; 3],
    pub mbr_0xb8: u8,  // offset: 0x00b8
    pub mbr_0xbc: u8,  // offset: 0x00bc
    _pad_0x00c0: [u8; 4],
    pub mbr_0xc4: u8,  // offset: 0x00c4
    pub mbr_0xc8: u8,  // offset: 0x00c8
    pub mbr_0xcc: u8,  // offset: 0x00cc
    pub mbr_0xd0: u8,  // offset: 0x00d0
    _pad_0x00d4: [u8; 4],
    pub mbr_0xd8: u8,  // offset: 0x00d8
    pub mbr_0xdc: u8,  // offset: 0x00dc
    pub mbr_0xe0: u8,  // offset: 0x00e0
    pub mbr_0xe4: u8,  // offset: 0x00e4
    pub mbr_0xe8: u8,  // offset: 0x00e8
    pub mbr_0xec: u8,  // offset: 0x00ec
    _pad_0x00f0: [u8; 4],
    pub cls_0x4050f7: GXCanvas,  // offset: 0x00f4
    pub mbr_0x18c: u8,  // offset: 0x018c
    pub mbr_0x190: u8,  // offset: 0x0190
    pub mbr_0x194: u8,  // offset: 0x0194
    pub cls_0x406db6: [u8; 8],  // offset: 0x0198
    _pad_0x01a0: [u8; 260],
    pub mbr_0x2a4: u8,  // offset: 0x02a4
    _pad_0x02a8: [u8; 16],
    pub mbr_0x2b8: u8,  // offset: 0x02b8
    pub mbr_0x2b9: u8,  // offset: 0x02b9
    _pad_0x02ba: [u8; 110],
    pub mbr_0x328: u8,  // offset: 0x0328
    pub mbr_0x32c: u8,  // offset: 0x032c
    pub mbr_0x330: u8,  // offset: 0x0330
    pub mbr_0x334: u8,  // offset: 0x0334
    pub mbr_0x338: u8,  // offset: 0x0338
    pub mbr_0x33c: u8,  // offset: 0x033c
    _pad_0x033d: [u8; 3],
    pub mbr_0x340: u8,  // offset: 0x0340
    _pad_0x0344: [u8; 1],
    pub mbr_0x345: u8,  // offset: 0x0345
    pub mbr_0x346: u8,  // offset: 0x0346
    pub mbr_0x347: u8,  // offset: 0x0347
    pub mbr_0x348: u8,  // offset: 0x0348
    pub mbr_0x349: u8,  // offset: 0x0349
    pub mbr_0x34a: u8,  // offset: 0x034a
    pub mbr_0x34b: u8,  // offset: 0x034b
    pub mbr_0x34c: u8,  // offset: 0x034c
    pub mbr_0x34d: u8,  // offset: 0x034d
    pub mbr_0x34e: u8,  // offset: 0x034e
    pub mbr_0x34f: u8,  // offset: 0x034f
    pub mbr_0x350: u8,  // offset: 0x0350
    pub mbr_0x351: u8,  // offset: 0x0351
    _pad_0x0352: [u8; 18],
    pub mbr_0x364: u8,  // offset: 0x0364
    _pad_0x0368: [u8; 8],
    pub mbr_0x370: u8,  // offset: 0x0370
    _pad_0x0374: [u8; 388],
    pub mbr_0x4f8: u8,  // offset: 0x04f8
}

// Size: 0x4fc (1276 bytes)
#[repr(C)]
pub struct ZTMiniMap_MaybeNot {
    pub cls_0x6313e4: [u8; 1276],  // offset: 0x0000
}

// Size: 0x15c (348 bytes)
#[repr(C)]
pub struct ZTPath {
    pub cls_0x62d950: ZTScenery,  // offset: 0x0000
    pub mbr_0x158: u8,  // offset: 0x0158
}

// Size: 0x175 (373 bytes)
#[repr(C)]
pub struct ZTPathType {
    pub cls_0x6303f4: ZTSceneryType,  // offset: 0x0000
    pub mbr_0x168: u8,  // offset: 0x0168
    pub mbr_0x16c: u8,  // offset: 0x016c
    pub mbr_0x170: u8,  // offset: 0x0170
    pub mbr_0x174: u8,  // offset: 0x0174
}

// Size: 0x18 (24 bytes)
#[repr(C)]
pub struct ZTResearchMgr {
    _pad_0x0000: [u8; 8],
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
}

// Size: 0x164 (356 bytes)
#[repr(C)]
pub struct ZTRubble {
    pub cls_0x62d950: ZTScenery,  // offset: 0x0000
    pub mbr_0x158: u8,  // offset: 0x0158
    pub mbr_0x15c: u8,  // offset: 0x015c
    pub mbr_0x160: u8,  // offset: 0x0160
}

// Size: 0x170 (368 bytes)
#[repr(C)]
pub struct ZTRubbleType {
    pub cls_0x6303f4: ZTSceneryType,  // offset: 0x0000
    pub mbr_0x168: u8,  // offset: 0x0168
    pub mbr_0x16c: u8,  // offset: 0x016c
}

// Size: 0x94 (148 bytes)
#[repr(C)]
pub struct ZTScenarioMgr {
    pub cls_0x630dac: *const u8,  // offset: 0x0000
}

// Size: 0x50 (80 bytes)
#[repr(C)]
pub struct ZTScenarioSimpleGoal {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x2c: u8,  // offset: 0x002c
    pub mbr_0x30: u8,  // offset: 0x0030
    pub mbr_0x34: u8,  // offset: 0x0034
    pub mbr_0x38: u8,  // offset: 0x0038
    pub mbr_0x3c: u8,  // offset: 0x003c
    pub mbr_0x40: u8,  // offset: 0x0040
    pub mbr_0x44: u8,  // offset: 0x0044
    pub mbr_0x48: u8,  // offset: 0x0048
    pub mbr_0x4c: u8,  // offset: 0x004c
}

// Size: 0x65 (101 bytes)
#[repr(C)]
pub struct ZTScenarioTimer {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    _pad_0x0014: [u8; 4],
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x2c: u8,  // offset: 0x002c
    pub mbr_0x30: u8,  // offset: 0x0030
    pub mbr_0x34: u8,  // offset: 0x0034
    pub mbr_0x38: u8,  // offset: 0x0038
    pub mbr_0x3c: u8,  // offset: 0x003c
    pub mbr_0x40: u8,  // offset: 0x0040
    pub mbr_0x44: u8,  // offset: 0x0044
    pub mbr_0x48: u8,  // offset: 0x0048
    pub mbr_0x4c: u8,  // offset: 0x004c
    pub mbr_0x50: u8,  // offset: 0x0050
    pub mbr_0x54: u8,  // offset: 0x0054
    pub mbr_0x58: u8,  // offset: 0x0058
    pub mbr_0x5c: u8,  // offset: 0x005c
    pub mbr_0x60: u8,  // offset: 0x0060
    pub mbr_0x61: u8,  // offset: 0x0061
    pub mbr_0x62: u8,  // offset: 0x0062
    pub mbr_0x63: u8,  // offset: 0x0063
    pub mbr_0x64: u8,  // offset: 0x0064
}

// Size: 0x158 (344 bytes)
#[repr(C)]
pub struct ZTScenery {
    pub cls_0x62d4b4: *const u8,  // offset: 0x0000
    pub mbr_0x154: u8,  // offset: 0x0154
}

// Size: 0x168 (360 bytes)
#[repr(C)]
pub struct ZTSceneryType {
    pub cls_0x62e28c: *const u8,  // offset: 0x0000
    _pad_0x0100: [u8; 68],
    pub mbr_0x144: u8,  // offset: 0x0144
    pub mbr_0x148: u8,  // offset: 0x0148
    pub mbr_0x14c: u8,  // offset: 0x014c
    pub mbr_0x150: u8,  // offset: 0x0150
    pub mbr_0x154: u8,  // offset: 0x0154
    pub mbr_0x158: u8,  // offset: 0x0158
    pub mbr_0x15c: u8,  // offset: 0x015c
    _pad_0x015d: [u8; 3],
    pub mbr_0x160: u8,  // offset: 0x0160
    pub mbr_0x164: u8,  // offset: 0x0164
}

// Size: 0x5 (5 bytes)
#[repr(C)]
pub struct ZTScriptMgr {
    _pad_0x0000: [u8; 4],
    pub mbr_0x4: u8,  // offset: 0x0004
}

// Size: 0x3d (61 bytes)
#[repr(C)]
pub struct ZTShow {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub cls_0x6355b8: *const u8,  // offset: 0x0018
}

// Size: 0xd0 (208 bytes)
#[repr(C)]
pub struct ZTShowInfo {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    _pad_0x0004: [u8; 204],
}

// Size: 0x41 (65 bytes)
#[repr(C)]
pub struct ZTShowMgr {
    _pad_0x0000: [u8; 4],
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0005: [u8; 3],
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub mbr_0x2c: u8,  // offset: 0x002c
    pub mbr_0x30: u8,  // offset: 0x0030
    _pad_0x0031: [u8; 3],
    pub cls_0x630d28: *const u8,  // offset: 0x0034
}

// Size: 0x1 (1 bytes)
#[repr(C)]
pub struct ZTShowScriptItem {
    _pad_0x0000: [u8; 1],
}

// Size: 0x1 (1 bytes)
#[repr(C)]
pub struct ZTShowScriptItem_conflict1 {
    _pad_0x0000: [u8; 1],
}

// Size: 0x14 (20 bytes)
#[repr(C)]
pub struct ZTShowScriptState {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    _pad_0x0006: [u8; 2],
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0xe: u8,  // offset: 0x000e
    pub mbr_0xf: u8,  // offset: 0x000f
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x11: u8,  // offset: 0x0011
    pub mbr_0x12: u8,  // offset: 0x0012
    pub mbr_0x13: u8,  // offset: 0x0013
}

// Size: 0x25 (37 bytes)
#[repr(C)]
pub struct ZTShowState {
    pub vftptr_0x0: *const *const u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x6: u8,  // offset: 0x0006
    pub mbr_0x7: u8,  // offset: 0x0007
    pub mbr_0x8: u8,  // offset: 0x0008
    _pad_0x0009: [u8; 3],
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
}

// Size: 0x39c (924 bytes)
#[repr(C)]
pub struct ZTStaff {
    pub cls_0x62fa44: ZTUnit,  // offset: 0x0000
    _pad_0x0260: [u8; 316],
}

// Size: 0x1f2 (498 bytes)
#[repr(C)]
pub struct ZTStaffType {
    pub cls_0x62e404: ZTUnitType,  // offset: 0x0000
    _pad_0x01b0: [u8; 4],
    pub mbr_0x1b4: u8,  // offset: 0x01b4
    pub mbr_0x1b8: u8,  // offset: 0x01b8
    pub mbr_0x1bc: u8,  // offset: 0x01bc
    pub mbr_0x1c0: u8,  // offset: 0x01c0
    pub mbr_0x1c4: u8,  // offset: 0x01c4
    pub mbr_0x1c8: u8,  // offset: 0x01c8
    pub mbr_0x1cc: u8,  // offset: 0x01cc
    pub mbr_0x1d0: u8,  // offset: 0x01d0
    pub mbr_0x1d4: u8,  // offset: 0x01d4
    pub mbr_0x1d8: u8,  // offset: 0x01d8
    pub mbr_0x1dc: u8,  // offset: 0x01dc
    pub mbr_0x1e0: u8,  // offset: 0x01e0
    pub mbr_0x1e4: u8,  // offset: 0x01e4
    pub mbr_0x1e8: u8,  // offset: 0x01e8
    pub mbr_0x1ec: u8,  // offset: 0x01ec
    pub mbr_0x1f0: u8,  // offset: 0x01f0
}

// Size: 0x1f8 (504 bytes)
#[repr(C)]
pub struct ZTTankExhibit {
    pub cls_0x632100: *const u8,  // offset: 0x0000
}

// Size: 0x1a8 (424 bytes)
#[repr(C)]
pub struct ZTTankFilter {
    pub cls_0x62d950: ZTScenery,  // offset: 0x0000
    pub mbr_0x158: u8,  // offset: 0x0158
    pub mbr_0x15c: u8,  // offset: 0x015c
    pub mbr_0x160: u8,  // offset: 0x0160
    pub mbr_0x164: u8,  // offset: 0x0164
    pub mbr_0x168: u8,  // offset: 0x0168
    pub mbr_0x16c: u8,  // offset: 0x016c
    pub mbr_0x170: u8,  // offset: 0x0170
    _pad_0x0174: [u8; 4],
    pub mbr_0x178: u8,  // offset: 0x0178
    pub mbr_0x17c: u8,  // offset: 0x017c
    pub mbr_0x180: u8,  // offset: 0x0180
    pub mbr_0x184: u8,  // offset: 0x0184
    pub mbr_0x188: u8,  // offset: 0x0188
    pub mbr_0x18c: u8,  // offset: 0x018c
    pub mbr_0x190: u8,  // offset: 0x0190
    _pad_0x0191: [u8; 3],
    pub mbr_0x194: u8,  // offset: 0x0194
    pub mbr_0x198: u8,  // offset: 0x0198
    pub mbr_0x19c: u8,  // offset: 0x019c
    pub mbr_0x1a0: u8,  // offset: 0x01a0
    pub mbr_0x1a4: u8,  // offset: 0x01a4
}

// Size: 0x1a4 (420 bytes)
#[repr(C)]
pub struct ZTTankFilterType {
    pub cls_0x6303f4: ZTSceneryType,  // offset: 0x0000
    pub mbr_0x168: u8,  // offset: 0x0168
    pub mbr_0x16c: u8,  // offset: 0x016c
    pub mbr_0x170: u8,  // offset: 0x0170
    pub mbr_0x174: u8,  // offset: 0x0174
    pub mbr_0x178: u8,  // offset: 0x0178
    pub mbr_0x17c: u8,  // offset: 0x017c
    pub mbr_0x180: u8,  // offset: 0x0180
    pub mbr_0x184: u8,  // offset: 0x0184
    pub mbr_0x188: u8,  // offset: 0x0188
    pub mbr_0x18c: u8,  // offset: 0x018c
    pub mbr_0x190: u8,  // offset: 0x0190
    pub mbr_0x194: u8,  // offset: 0x0194
    pub mbr_0x198: u8,  // offset: 0x0198
    pub mbr_0x19c: u8,  // offset: 0x019c
    pub mbr_0x1a0: u8,  // offset: 0x01a0
}

// Size: 0x474 (1140 bytes)
#[repr(C)]
pub struct ZTTankWall {
    _pad_0x0000: [u8; 1104],
    pub mbr_0x450: u8,  // offset: 0x0450
    pub mbr_0x454: u8,  // offset: 0x0454
    pub mbr_0x458: u8,  // offset: 0x0458
    pub mbr_0x45c: u8,  // offset: 0x045c
    pub mbr_0x460: u8,  // offset: 0x0460
    pub mbr_0x464: u8,  // offset: 0x0464
    pub mbr_0x465: u8,  // offset: 0x0465
    pub mbr_0x466: u8,  // offset: 0x0466
    _pad_0x0467: [u8; 5],
    pub mbr_0x46c: u8,  // offset: 0x046c
    pub mbr_0x470: u8,  // offset: 0x0470
}

// Size: 0x1c4 (452 bytes)
#[repr(C)]
pub struct ZTTankWallType {
    pub cls_0x63034c: ZTFenceType,  // offset: 0x0000
    pub mbr_0x1a4: u8,  // offset: 0x01a4
    pub mbr_0x1a8: u8,  // offset: 0x01a8
    pub mbr_0x1ac: u8,  // offset: 0x01ac
    pub mbr_0x1b0: u8,  // offset: 0x01b0
    pub mbr_0x1b4: u8,  // offset: 0x01b4
    pub mbr_0x1b8: u8,  // offset: 0x01b8
    pub mbr_0x1bc: u8,  // offset: 0x01bc
    pub mbr_0x1c0: u8,  // offset: 0x01c0
}

// Size: 0xc (12 bytes)
#[repr(C)]
pub struct ZTThoughtMgr {
    _pad_0x0000: [u8; 8],
    pub mbr_0x8: u8,  // offset: 0x0008
}

// Size: 0x260 (608 bytes)
#[repr(C)]
pub struct ZTUnit {
    pub cls_0x62fd58: BFUnit,  // offset: 0x0000
    _pad_0x0214: [u8; 76],
}

// Size: 0x1b0 (432 bytes)
#[repr(C)]
pub struct ZTUnitType {
    pub cls_0x62e4d8: BFUnitType,  // offset: 0x0000
    pub mbr_0x144: u8,  // offset: 0x0144
    pub mbr_0x148: u8,  // offset: 0x0148
    pub mbr_0x14c: u8,  // offset: 0x014c
    pub map_footprint: u8,  // offset: 0x0150
    pub mbr_0x154: u8,  // offset: 0x0154
    pub mbr_0x156: u8,  // offset: 0x0156
    pub mbr_0x158: u8,  // offset: 0x0158
    _pad_0x015a: [u8; 2],
    pub mbr_0x15c: u8,  // offset: 0x015c
    pub mbr_0x160: u8,  // offset: 0x0160
    pub mbr_0x164: u8,  // offset: 0x0164
    pub mbr_0x168: u8,  // offset: 0x0168
    pub mbr_0x16c: u8,  // offset: 0x016c
    pub mbr_0x170: u8,  // offset: 0x0170
    pub mbr_0x174: u8,  // offset: 0x0174
    pub mbr_0x178: u8,  // offset: 0x0178
    pub mbr_0x17c: u8,  // offset: 0x017c
    pub mbr_0x17d: u8,  // offset: 0x017d
    pub mbr_0x17e: u8,  // offset: 0x017e
    pub mbr_0x17f: u8,  // offset: 0x017f
    pub mbr_0x180: u8,  // offset: 0x0180
    pub mbr_0x184: u8,  // offset: 0x0184
    pub mbr_0x188: u8,  // offset: 0x0188
    pub mbr_0x18c: u8,  // offset: 0x018c
    pub mbr_0x190: u8,  // offset: 0x0190
    pub mbr_0x194: u8,  // offset: 0x0194
    pub mbr_0x198: u8,  // offset: 0x0198
    pub mbr_0x19c: u8,  // offset: 0x019c
    pub mbr_0x1a0: u8,  // offset: 0x01a0
    pub mbr_0x1a4: u8,  // offset: 0x01a4
    pub mbr_0x1a8: u8,  // offset: 0x01a8
    pub mbr_0x1ac: u8,  // offset: 0x01ac
}

// Size: 0x218 (536 bytes)
#[repr(C)]
pub struct ZTWorldMgr {
    pub cls_0x630c50: *const u8,  // offset: 0x0000
    _pad_0x0118: [u8; 16],
    pub cls_0x40e420: GXMixer,  // offset: 0x0128
    _pad_0x018d: [u8; 3],
    pub mbr_0x190: u8,  // offset: 0x0190
    _pad_0x0194: [u8; 12],
    pub mbr_0x1a0: u8,  // offset: 0x01a0
    pub mbr_0x1a4: u8,  // offset: 0x01a4
    pub mbr_0x1a8: u8,  // offset: 0x01a8
    pub mbr_0x1ac: u8,  // offset: 0x01ac
    pub mbr_0x1b0: u8,  // offset: 0x01b0
    pub mbr_0x1b4: u8,  // offset: 0x01b4
    pub mbr_0x1b5: u8,  // offset: 0x01b5
    _pad_0x01b6: [u8; 2],
    pub mbr_0x1b8: u8,  // offset: 0x01b8
    _pad_0x01bc: [u8; 12],
    pub mbr_0x1c8: u8,  // offset: 0x01c8
    pub mbr_0x1cc: u8,  // offset: 0x01cc
    pub mbr_0x1d0: u8,  // offset: 0x01d0
    pub mbr_0x1d4: u8,  // offset: 0x01d4
    pub mbr_0x1d8: u8,  // offset: 0x01d8
    pub mbr_0x1dc: u8,  // offset: 0x01dc
    pub mbr_0x1dd: u8,  // offset: 0x01dd
    _pad_0x01de: [u8; 2],
    pub cls_0x630bc0: *const u8,  // offset: 0x01e0
    pub cls_0x630bc0_1: *const u8,  // offset: 0x01e8
    _pad_0x01f0: [u8; 8],
    pub mbr_0x1f8: u8,  // offset: 0x01f8
    pub mbr_0x1fc: u8,  // offset: 0x01fc
    pub mbr_0x200: u8,  // offset: 0x0200
    _pad_0x0204: [u8; 4],
    pub mbr_0x208: u8,  // offset: 0x0208
    pub mbr_0x20c: u8,  // offset: 0x020c
    pub mbr_0x210: u8,  // offset: 0x0210
    pub mbr_0x214: u8,  // offset: 0x0214
}

// Size: 0x154 (340 bytes)
#[repr(C)]
pub struct ZooStatus {
    _pad_0x0000: [u8; 332],
    pub mbr_0x14c: u8,  // offset: 0x014c
    pub mbr_0x150: u8,  // offset: 0x0150
}

// Size: 0x5c (92 bytes)
#[repr(C)]
pub struct std_tree {
    pub mbr_0x0: u8,  // offset: 0x0000
    pub mbr_0x4: u8,  // offset: 0x0004
    pub mbr_0x8: u8,  // offset: 0x0008
    pub mbr_0xc: u8,  // offset: 0x000c
    pub mbr_0x10: u8,  // offset: 0x0010
    pub mbr_0x14: u8,  // offset: 0x0014
    pub mbr_0x18: u8,  // offset: 0x0018
    pub mbr_0x1c: u8,  // offset: 0x001c
    pub mbr_0x20: u8,  // offset: 0x0020
    pub mbr_0x24: u8,  // offset: 0x0024
    pub mbr_0x28: u8,  // offset: 0x0028
    pub map_x_size: u8,  // offset: 0x002c
    pub map_y_size: u8,  // offset: 0x0030
    pub mbr_0x34: u8,  // offset: 0x0034
    pub tile_array_start: u8,  // offset: 0x0038
    pub mbr_0x3c: u8,  // offset: 0x003c
    pub mbr_0x40: u8,  // offset: 0x0040
    pub mbr_0x44: u8,  // offset: 0x0044
    _pad_0x0045: [u8; 3],
    pub mbr_0x48: u8,  // offset: 0x0048
    pub mbr_0x4c: u8,  // offset: 0x004c
    pub mbr_0x50: u8,  // offset: 0x0050
    pub mbr_0x54: u8,  // offset: 0x0054
    _pad_0x0055: [u8; 3],
    pub mbr_0x58: u8,  // offset: 0x0058
}
